;================================================== ARM ;==================================================

(define "tiger_p_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/ferdinand/start"}
		{link_sound "engine_stop"		"vehicle/engine/ferdinand/stop"}
		{link_sound "engine_idle"		"vehicle/engine/ferdinand/idle"}
		{link_sound "engine_full"		"vehicle/engine/ferdinand/full"}
		{link_sound "exhaust"			"vehicle/engine/ferdinand/exhaust"}
		{link_sound "move"				"vehicle/tracks/ferdinand/"}
		{link_sound "rotate_turret"		"vehicle/turret/hydraulic/hydraulic_heavy"}
	}
)

(define "t44_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/t44/start"}
		{link_sound "engine_stop"		"vehicle/engine/t44/stop"}
		{link_sound "engine_idle"		"vehicle/engine/t44/idle"}
		{link_sound "engine_full"		"vehicle/engine/t44/full"}
		{link_sound "exhaust"		"vehicle/engine/t44/exhaust"}
		{link_sound "move"			"vehicle/tracks/t44/"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)

(define "vk3601h_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/pz6/start"}
		{link_sound "engine_stop"		"vehicle/engine/pz6/stop"}
		{link_sound "engine_idle"		"vehicle/engine/pz6/idle"}
		{link_sound "engine_full"		"vehicle/engine/pz6/full"}
		{link_sound "exhaust"			"vehicle/engine/pz6/exhaust"}
		{link_sound "move"				"vehicle/tracks/pz6/"}
		{link_sound "rotate_turret"		"vehicle/turret/hydraulic/hydraulic_heavy"}
	}
)

(define "pzkpfw_tiger_h1_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/pz6/start"}
		{link_sound "engine_stop"		"vehicle/engine/pz6/stop"}
		{link_sound "engine_idle"		"vehicle/engine/pz6/idle"}
		{link_sound "engine_full"		"vehicle/engine/pz6/full"}
		{link_sound "exhaust"			"vehicle/engine/pz6/exhaust"}
		{link_sound "move"				"vehicle/tracks/pz6/"}
		{link_sound "rotate_turret"		"vehicle/turret/hydraulic/hydraulic_heavy"}
	}
)

(define "t44_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/is/start"}
		{link_sound "engine_stop"		"vehicle/engine/is/stop"}
		{link_sound "engine_idle"		"vehicle/engine/is/idle"}
		{link_sound "engine_full"		"vehicle/engine/is/full"}
		{link_sound "exhaust"			"vehicle/engine/is/exhaust"}
		{link_sound "move"				"vehicle/tracks/is/"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_heavy"}
	}
)

(define "volvo_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/blitz/start"}
		{link_sound "engine_stop"		"vehicle/engine/blitz/stop"}
		{link_sound "engine_idle"		"vehicle/engine/blitz/idle"}
		{link_sound "engine_full"		"vehicle/engine/blitz/full"}
		{link_sound "exhaust"			"vehicle/engine/blitz/exhaust"}
		{link_sound "move"				"vehicle/wheels/truck"}
		{link_sound "brake"				"vehicle/wheels/brake"}
		{link_sound "rotate_turret"		"vehicle/turret/cannon/small"}
		{link_sound "rotate_gun"		"vehicle/turret/cannon/small"}

		{link_sound "open_left"			"vehicle/doors/blitz/open_left"}
		{link_sound "open_right"		"vehicle/doors/blitz/open_right"}
		{link_sound "open_rear"			"vehicle/doors/blitz/open_rear"}
		{link_sound "close_rear"		"vehicle/doors/blitz/close_rear"}
		{link_sound "open_radio"		"vehicle/doors/blitz/open_radio"}
	}
)

