{difficulty
	(include "difficulty_generic.inc")
	{any	;// temp to give enemy stats
		{health 1.0}				; health multiplier from soldier settings
		{accuracy 0.5}
	}
	{enemy	;// not working in coop
		{health 1.0}				; health multiplier from soldier settings
		{accuracy 0.5}
	}
	{ally
		{health 1.0}				; health multiplier from soldier settings
		{accuracy 0.5}
	}
	{player
		{health 1.0}				; health multiplier from soldier settings
		{accuracy 0.5}
	}
}
