;============================================== TSL script injector ==============================

;//	{on spawn 
;//		{if not tagged "_user" 
;//	;	else tagged "bot"
;//		else tagged "_bot"
;//			{delay 0.02 
;//				{tags add "no_trophy"}
;//				
;//			}
;//		}
;//	}

;// {on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}

;============================================== TSL BEGIN =======================================

;============================================== TSL GER =========================================
;;--------------------------------------------- TSL GER tanks -----------------------------------
;;--------------------------------------------- TSL GER tanks MODed -----------------------------
;//-------------------------------------------- TSL GER tanks MODed light -----------------------

{"panzer1f_stand tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"pz38h_w40 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"pz38h_735 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL GER tanks MODed medium ----------------------

{"nbfz tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"panzer4b tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"panzer3h tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"panzer3j tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"panzer4d tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"panzer4f2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t34_kwk37 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"vk3601h tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"vk_3002 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"panzer5d tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"strumpanzer5g tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"panther_II_88 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"pzvd_pziv_turret tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"panther_ii-hd tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"coelian_I tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"coelian_ii tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"bergepanther tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL GER tanks MODed heavy -----------------------

{"panzerb2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"flammpanzer_b2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"char_2c_bis tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"char_2c_bis_armored tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"vk6501h tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"pz756r tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"tiger1h_early tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"tiger_p tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"pz6p_panzerbefehiswagen tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"tiger2p tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"tiger2h tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//{"pzkpfw_6_ausf_b_tiger_sla16 tank"
;//{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
;//}

{"pz6bh_105mm tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"bergetiger tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"lowehd tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL GER tanks MODed s.heavy --------------------

{"e_100c tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"e_100b tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"e_100a tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL GER tanks MODed Hunter --------------------

{"lorraine_37l tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sdkfz10_pak38 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t26_pak9738_ger tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"dicker_max tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sturer_emil tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"nashorn tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL GER tanks MODed TD -----------------------

{"sig33b tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"stug3f tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"jagdpanzer4_l48_early tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"ferdinand tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"jagdpanther tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"jagdtiger88 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"jagdtiger tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sturmpanzer4 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sturmtiger tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL GER tanks MODed SPG -----------------------

{"bison tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"bison2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"geschuetzwagen_ivb tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//	{"wespe tank"
;//	{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
;//	}


{"grille_k tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"hummel tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"600mm_thor tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;;--------------------------------------------- TSL GER vehicles --------------------------------

{"sdkfz8_flak18 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sdkfz251d_1_stuka tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sdkfz251d_17 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"panzerwerfer42 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;;--------------------------------------------- TSL GER btr MODed --------------------------------

{"zgkw303f"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;;--------------------------------------------- TSL GER cannons MODed --------------------------------
{"v2_a4"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}


;============================================== TSL USSR ========================================
;;--------------------------------------------- TSL USSR tanks MODed ----------------------------------
;//-------------------------------------------- TSL USSR tanks MODed light -----------------------

{"bt2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"bt7a tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"rbt_5 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"bt2_25mm_auto_rus tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL USSR tanks MODed Medium -----------------------

{"t28_85 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"it_3 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"a32_39 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t3476_40 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t3476_41e tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t3457_41 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t3485_43 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t3485_43 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t3485_44_flame tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t3485_44a_flame tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t44_122 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t4485 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t44100 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-	{"panther_5 tank"
;//-	{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
;//-	}

;//-------------------------------------------- TSL USSR tanks MODed Heavy -----------------------

{"t35 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv1_39 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv2_39 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"matilda_f96 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"smk tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv2_40 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv1_40 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv1_40e tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv1_41 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv8 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv2_zis6 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv_220 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv220 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-	{"object248 tank"
;//-	{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
;//-	}


{"kv1_122 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-	{"kv-3 tank"
;//-	{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
;//-	}

{"kv-220 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv5 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"kv4b tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"is2_43 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"is2_44 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//{"is_4 tank"
;//{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
;//}

{"is_4_100 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-	{"is_100 tank"
;//-	{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
;//-	}

;//{"is_3 tank"
;//{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
;//}

{"is_6 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"is_7 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL USSR tanks MODed Super Heavy -----------------------

{"t_42 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL USSR tanks MODed Hunter -----------------------

{"zis30 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"marder139_rus tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"su57b tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL GER tanks MODed TD -----------------------

{"su100y tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"su122p tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"su122e tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"su152 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//	{"su152_late tank"
;//	{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
;//	}

{"su100 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"wolverine tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"isu152 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"isu122s tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"isu_152_2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL GER tanks MODed SPG -----------------------

{"su14 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"su14_2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"su26 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;;--------------------------------------------- TSL GER vehicles MODed --------------------------------


;;--------------------------------------------- TSL GER cars MODed --------------------------------

{"zis6_bm8_48 car"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"zis6_bm13_16 car"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"bm31_12 car"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"bm13_studebaker car"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;============================================== TSL FIN ========================================
;;--------------------------------------------- TSL FIN tanks ----------------------------------

{"kv1_40e_fin tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}
;;--------------------------------------------- TSL FIN tanks MODed ----------------------------------


{"smk_fin tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}


;;--------------------------------------------- TSL FIN vehicles -------------------------------


;============================================== TSL USA ========================================
;;--------------------------------------------- TSL USA tanks ----------------------------------

{"m4a3_calliope tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"m4a3_105_hvss tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"m4a3_105 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"m4a1_75_mid_armor tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"m4a1_75_dd tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"m4_75_early_armor tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"m4_105 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"m3_lee tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t26e4 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"m26_pershing tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}


;;--------------------------------------------- TSL USA tanks MODed ----------------------------------

{"m2a1_medium tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"m2e1_medium_flamm tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"m2_medium tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"us_m4_improved tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"T_14 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"us_m6a1 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"us_m3_recovery tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"us_m19 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t18_hmc tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"us_t95_gen2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"us_t95 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"US_t34 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"us_t32e1 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"US_t30 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"us_m6a2e1 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t_14 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t93_hmc tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"t92_hmc tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"us_t55e1 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"US_t18e2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}



;;--------------------------------------------- TSL USA vehicles -------------------------------


;============================================== TSL ENG =========================================
;;--------------------------------------------- TSL ENG tanks -----------------------------------
;;--------------------------------------------- TSL ENG tanks MODed -----------------------------
;//-------------------------------------------- TSL ENG tanks MODed light -----------------------

{"cruiser_mk1_cs tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"cruiser_mk2a_cs tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"cruiser_mk4 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"crusader_aa_mk1 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL ENG tanks MODed medium -----------------------

{"matilda2_mk1 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"matilda2_mk3 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"cromwell4_tulip tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"challenger_a30 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sherman1c_armor tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sherman1c_tulip_hybrid tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sherman1b tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sherman3_early tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sherman5c tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL ENG tanks MODed heavy -----------------------

{"churchill_mk1 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"churchill_mk2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"churchill_mk3_l50 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"churchill_mk3_l50_late tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"churchill_mk4_l50 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"churchill_mk4_avre tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"achilles_mk2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

;//-------------------------------------------- TSL ENG tanks MODed SPG -----------------------



{"bishop tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}

{"sexton_mk2 tank"
{on spawn {if not tagged "_user" {if not user_control {if not tagged "no_trophy" {tags add "no_trophy"}}}}}
}




;============================================== TSL END =======================================