{"105mm_flak38_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"88mm_flak18_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"105mm_lefh18_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"20mm_itk40_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"20mm_itk35_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"75mm_itk37_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ds39_fin_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"20mm_itk40_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"57mm_m1_bot" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"inf_crate_usa_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"75mm_itk37_stat" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"76mm_itk31_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"105mm_k34_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"inf_crate_rus_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"85mm_52k_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"203mm_b4_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"122mm_m1910_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"120mm_pm38_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"dshk_aa_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"ussr_4x_maxima_foxhole" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"maxim_x4_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"50mm_flak41_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"37mm_61k_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"122mm_m30_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"75mm_itk44_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"107mm_m1910_30_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"81mm_m1_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"105mm_m2a1_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"40mm_itk38b_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"75mm_pak9738_late_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"88mm_flak18_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"80mm_sgrw34_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"120mm_krh40_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"20mm_itk35_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"120mm_sgrw42_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"105mm_flak38_stat" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"mg34_tripod_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"88mm_flak18_bot" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"50mm_flak41_bunker_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"150mm_sw34_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"150mm_sw34_ger" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"150mm_sw34" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"ZP_3154B" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"mg42_tripod_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"50mm_kwk39_platform" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}