; File: 		unit_arm.inc
; Catalog: 		set\registry
; Created by: 	Max Drechsler
; Created:		x.xx.xxxx
; Modify by:	Max Drechsler
; Modify:		11.09.2026
; DSL:			GEM ENGINE 2 Gates of Hell
; Version:		1.1
; Description: 	Vehicle view Definitions for new units


;===================================================== Modded BEGIN
;===================================================== Modded GER
;----------------------------------------------------- Modded GER AIR

			{"ju-52"
				{vehicle_view "c47_d"}
			}

			{"ju-52_para_plane"
				{vehicle_view "c47_d"}
			}

			{"ju-52_para_plane_player"
				{vehicle_view "airborne"}
			}
			
			{"bf109_e4b_ai"
				{vehicle_view "bf109_e4b"}
			}
			
			{"bf109_f2"
				{vehicle_view "bf109_g6"}
			}
			
			{"bf109_f2_ai"
				{vehicle_view "bf109_g6"}
			}

;//			{"bf109_f4"
;//				{vehicle_view "bf109_g6"}
;//			}

			{"bf109_f4_ai"
				{vehicle_view "bf109_g6"}
			}

;//			{"bf109_g6"
;//				{vehicle_view "bf109_g6"}
;//			}

			{"bf109_g6_ai"
				{vehicle_view "bf109_g6"}
			}

			{"bf109_g6_rocket_ai"
				{vehicle_view "bf109_g6"}
			}

;//			{"ju-87"
;//				{vehicle_view "bf110_e2"}
;//			}
			
			{"ju-87_ai"
				{vehicle_view "bf110_e2"}
			}			

;//			{"bf110_e2"
;//				{vehicle_view "bf110_e2"}
;//			}

			{"bf110_e2_ai"
				{vehicle_view "bf110_e2"}
			}

			{"bf110_e2_1000kg_ai"
				{vehicle_view "bf110_e2"}
			}

			{"bf110_e2_rocket_ai"
				{vehicle_view "bf110_e2"}
			}

			{"bf110_e2_flam_500kg_ai"
				{vehicle_view "bf110_e2"}
			}
					
;//			{"bf110_f4"
;//				{vehicle_view "bf110_e2"}
;//			}

			{"bf110_f4_ai"
				{vehicle_view "bf110_e2"}
			}			

			{"me-262_a1_new"
				{vehicle_view "airborne"}
			}
			
			{"me-262_a1_new_ai"
				{vehicle_view "airborne"}
			}

			{"me_262_50mm_ai"
				{vehicle_view "yak1_ser69"}
			}

			{"me_262_rockets_210x2_ai"
				{vehicle_view "yak1_ser69"}
			}

			{"ai_fi156"
				{vehicle_view "fi156"}
			}
								
;----------------------------------------------------- Modded GER TANKS

			{"lowehd"
				{vehicle_view "tiger2h"}
			}

			{"t26_pak9738"
				{vehicle_view "marder2"}
			}
			
			{"t26_pak9738_ger"
				{vehicle_view "marder2"}
			}

			{"panther_f"
				{vehicle_view "panzer5"}
			}

			{"marder3h"
				{vehicle_view "marder2"}
			}

			{"marder139"
				{vehicle_view "marder2"}
			}
			
			{"marder139_rus"
				{vehicle_view "marder2"}
			}

			{"panther_ii_88"
				{vehicle_view "panzer5"}
			}

			{"panther_ii-hd"
				{vehicle_view "panzer5"}
			}

			{"t34_kwk37"
				{vehicle_view "t3457_41"}
			}

			{"bergetiger"
				{vehicle_view "tiger_1h"}
			}

;//			{"dicker_max_iva"
;//				{vehicle_view "tank_destroyer"}
;//			}

			{"pzkpfw_tiger_h1"
				{vehicle_view "tiger_1h"}
			}
			
			{"tiger1h_early"
				{vehicle_view "tiger_1h"}
			}

			{"tiger_p"
				{vehicle_view "tiger_1h"}
			}
			
			{"PzKw753_40"
				{vehicle_view "kv1_41"}
			}
			
			{"PzKw753_41"
				{vehicle_view "kv1_41"}
			}

			{"PzKw755_S"
				{vehicle_view "kv1s"}
			}
									
			{"pzkw754"
				{vehicle_view "kv2"}
			}
			
			{"pzkw747_85"
				{vehicle_view "t34_85"}
			}

			{"vk3601h"
				{vehicle_view "vk3601h"}
			}

			{"panzerjager1_b"
				{vehicle_view "panzerjager1"}
			}
			
			{"pzvd_pziv_turret"
				{vehicle_view "panzer5"}
			}
			
			{"pzvd_pziv_turret_bare"
				{vehicle_view "panzer5"}
			}
			
			{"panzer_2j"
				{vehicle_view "pz2f"}
			}

			{"vk6501h"
				{vehicle_view "vk6501h"}
			}

			{"pzkw747_57_43"
				{vehicle_view "t34_76"}
			}
			
			{"pzkw747_76_41"
				{vehicle_view "t3476_41"}
			}

			{"pzkw747_85"
				{vehicle_view "t34_85"}
			}	

			{"stug3a"
				{vehicle_view "stug3b"}
			}

			{"stug4g"
				{vehicle_view "stug3g"}
			}
			
;//			{"m4a4_firefly_ger"
;//				{vehicle_view "m4a3_76w"}			
;//			}	
			
			{"jagdtiger88"
				{vehicle_view "jagdtiger"}
			}

;----------------------------------------------------- Modded-ROAm GER TANKS
			
			{"pzkpfw_kw_la753r"
				{vehicle_view "kv1_41"}
			}					
			
			{"pzkpfw_kw_la753r_ger"
				{vehicle_view "kv1_41"}
			}
			
;----------------------------------------------------- Modded GER GUNS

			{"solothurn_s18_100"
				{vehicle_view "cannon_20mm_l39"}
			}

			{"mg131_tripod"
				{vehicle_view "m2_50cal_tripod"}
			}
			
			{"heavy_mg_mg131_tripod"
				{vehicle_view "m2_50cal_tripod"}
			}

			{"mg42_tripod"
				{vehicle_view "m2_30cal_tripod"}
			}

			{"mg34_tripod"
				{vehicle_view "m2_30cal_tripod"}
			}

			{"mg131_lafette"
				{vehicle_view "mg_stand"}
			}

			{"105mm_flak38"
				{vehicle_view "flak18"}
			}	

			{"20mm_kwk30_inf"
				{vehicle_view "20mm_l39"}
			}
			
			{"105mm_flak38"
				{vehicle_view "88mm_flak36"}
			}			
			
			{"flak38"
				{vehicle_view "flak38"}
			}
			
			{"75mm_pak41"
				{vehicle_view "cannon_75mm_pak9738"}
			}

;----------------------------------------------------- Modded-ROA GER GUNS
			
			{"9cm_flak41i"
				{vehicle_view "52k"}
			}

			{"20mm_kwk30_inf"
				{vehicle_view "cannon_20mm_l39"}
			}
			
;----------------------------------------------------- Modded GER TRUCKS & BTR

			{"volvo"
				{vehicle_view "volvo"}
			}

			{"sdkfz_251_21"
				{vehicle_view "sdkfz234_4"}
			}
			
			{"volvo_art"
				{vehicle_view "volvo_art"}
			}
			
			{"volvo_weapon"
				{vehicle_view "volvo"}
			}
			
			{"zgkw303f"
				{vehicle_view "armored_car_track"}
			}

			{"sdkfz251cap"
				{vehicle_view "sdkfz251c"}
			}
			
			{"ba6_roa"
				{vehicle_view "ba6"}
			}
			
			{"ba11"
				{vehicle_view "ba6"}
			}
			
			{"voroshilovets"
				{vehicle_view "t20"}
			}

			{"zgkw303f"
				{vehicle_view "armored_car_track"}
			}

			{"blitz3_6_open"
				{vehicle_view "car"}
			}
			
			{"sdkfz10_open"
				{vehicle_view "sdkfz10"}
			}
			
			{"sdkfz6_ammo"
				{vehicle_view "sdkfz10"}
			}

			{"sdkfz6_weapon"
				{vehicle_view "sdkfz10"}
			}

			{"sdkfz6_cargo"
				{vehicle_view "sdkfz10"}
			}
			
			{"sdkfz6_supply"
				{vehicle_view "sdkfz10"}
			}
			
			{"sdkfz251c_mg131"
				{vehicle_view "sdkfz251c"}
			}	
			
			{"sdkfz251c_tarp"
				{vehicle_view "sdkfz251c"}
			}

			{"sdkfz251d_2xgrw42"
				{vehicle_view "sdkfz251c_2"}
			}			
			
			{"kubelwagen_open"
				{vehicle_view "kubelwagen"}
			}	
			
			{"blitz3_6_medic"
				{vehicle_view "car"}
			}		

			{"opel_blitz_omnibus"
				{vehicle_view "car"}
			}	
			
			{"blitz3_6_raketenwerfer"
				{vehicle_view "car"}
			}
				
;==================================================== Modded USSR
;---------------------------------------------------- Modded USSR AIR

;//			{"yak1_ser69"
;//				{vehicle_view "yak1_ser69"}
;//			}
			
			{"yak1_ser69_ai"
				{vehicle_view "yak1_ser69"}
			}

;//			{"il2_mod42"
;//				{vehicle_view "il2_mod42"}
;//			}

			{"il2_mod42_ai"
				{vehicle_view "il2_mod42"}
			}

			{"il2_mod41"
				{vehicle_view "il2_mod42"}
			}
					
			{"il2_mod41_ai"
				{vehicle_view "il2_mod42"}
			}

			{"li-2"
				{vehicle_view "c47_d"}
			}
			
;//			{"li-2_ai"
;//				{vehicle_view "c47_d"}
;//			}
				
			{"rus-b25"
				{vehicle_view "airborne"}
			}

			{"rus-b25_ai"
				{vehicle_view "airborne"}
			}
			
			{"ussr-p-39"
				{vehicle_view "airborne"}
			}
	
			{"ussr-p-39_ai"
				{vehicle_view "airborne"}
			}

			{"ai_po2"
				{vehicle_view "po2"}
			}

			{"po2_flame"
				{vehicle_view "po2"}
			}

			{"po2_rocket"
				{vehicle_view "po2"}
			}
				
;---------------------------------------------------- Modded USSR CARS

			{"m72o"
				{vehicle_view "m72"}
			}

			{"gaz67_open"
				{vehicle_view "gaz67"}
			}	
			
			{"zis5_open"
				{vehicle_view "zis5"}
			}		

			{"zis5_61k"
				{vehicle_view "gaz_aa"}
			}

			{"gaz_aaa_open"
				{vehicle_view "gaz"}
			}
	
			{"ba64d"
				{vehicle_view "ba64"}
			}

			{"m2_halftrack_rus"
				{vehicle_view "m2_halftrack"}
			}
			
;----------------------------------------------------- USSR TANKS
			{"kv-3"
				{vehicle_view "kv1s"}
			}
			{"zsu_37"
				{vehicle_view "t60"}
			}

			{"kv1_122"
				{vehicle_view "kv1_42"}
			}

			{"kv220"
				{vehicle_view "kv1s"}
			}
			
			{"matilda_f96"
				{vehicle_view "matilda2_mid"}
			}

			{"it_3"
				{vehicle_view "t3476_40"}
			}
			
			{"a32_39"
				{vehicle_view "t3476_40"}
			}

			{"t34_44supply"
				{vehicle_view "t34_85"}
			}		
			
			{"kv2_39"
				{vehicle_view "kv2"}
			}			
			
			{"t3485_43"
				{vehicle_view "t34_85"}
			}

			{"kv122"
				{vehicle_view "kv1s"}
			}

			{"kv2_zis6"
				{vehicle_view "kv1s"}
			}

			{"t34_44nohead"
				{vehicle_view "t34_85"}
			}	
			
			{"su122e"
				{vehicle_view "su122"}
			}
			
			{"94km"
				{vehicle_view "94km"}
			}
			
			{"t44100"
				{vehicle_view "t44"}
			}

			{"su14"
				{vehicle_view "su100y"}
			}
			
			{"su57b"
				{vehicle_view "su57b"}
			}
			
			{"su5"
				{vehicle_view "su26"}
			}

			{"bt2_25mm_auto_rus"
				{vehicle_view "bt2_25mm_auto_rus"}
			}
	
			{"bt2_25mm_rus"
				{vehicle_view "bt2_25mm_rus"}
			}
	
			{"bt2_2gun_rus"
				{vehicle_view "bt2_2gun_rus"}
			}
	
			{"bt2_da2_2gun_rus"
				{vehicle_view "bt2_da2_2gun_rus"}
			}
	
			{"bt2_supply_rus"
				{vehicle_view "bt2_supply_rus"}
			}

			{"wolverine"
				{vehicle_view "m10_gmc"}			
			}	
			
			{"su122p"
				{vehicle_view "su85"}
			}
			
			{"t4485"
				{vehicle_view "t44"}
			}	
			
			{"object248"
				{vehicle_view "is1_43"}
			}
			
			{"is_100"
				{vehicle_view "is1_43"}
			}
			
;----------------------------------------------------- Modded USSR GUNS		

			{"kpv_1944"
				{vehicle_view "mg_stand"}
			}

			{"125mm_pma40_prot"
				{vehicle_view "cannon_120mm_pm38"}
			}	
			
			{"82mm_bm37_ai"
				{vehicle_view "mortar_rus"}
			}

			{"ZP_3154B"
				{vehicle_view "special_150mm_sw34"}
			}

;----------------------------------------------------- Modded USSR TRUCKS		

			{"cckw_ussr"
				{vehicle_view "cckw"}
			}

			{"dshk_carrier_rus"
				{vehicle_view "universal"}
			}
			
			{"m3a1e1_dshk"
				{vehicle_view "armored_car_m3a1e1"}
			}

;==================================================== Modded FIN
;---------------------------------------------------- Modded FIN Tanks

	{"smk_fin"
		{vehicle_view "smk"}
	}

;---------------------------------------------------- Modded FIN Aircraft

;//			{"po2_fin"
;//				{vehicle_view "po2"}
;//			}
			
			{"po2_fin_ai"
				{vehicle_view "po2"}
			}

;//			{"fokker_fin"
;//				{vehicle_view "yak1_ser69"}
;//			}
			
			{"fokker_fin_ai"
				{vehicle_view "yak1_ser69"}
			}

			{"bf109_g6_fin"
				{vehicle_view "bf109_g6"}
			}

			{"bf109_g6_fin_ai"
				{vehicle_view "bf109_g6"}
			}

;==================================================== Modded USA
;---------------------------------------------------- Modded USA Tanks

	{"m2a4_stuart"
		{vehicle_view "m3_stuart_early"}
	}
	
;---------------------------------------------------- Modded USA Aircraft

	{"c-47_skytrain_dakota"
		{vehicle_view "airborne"}
	}

	{"c-47_skytrain_dakota_para_plane_player"
		{vehicle_view "airborne"}
	}

	{"c47_d_para_plane_ai"
		{vehicle_view "c47_d"}
	}

	{"c47_d_para_plane_player"
		{vehicle_view "c47_d"}
	}

	{"us-piper_j-3"
		{vehicle_view "fi156"}
	}

	{"us-piper_j-3_ai"
		{vehicle_view "fi156"}
	}

	{"us-p-39"
		{vehicle_view "airborne"}
	}
	
	{"us-p-39_ai"
		{vehicle_view "airborne"}
	}

	{"p-51mustang"
		{vehicle_view "airborne"}
	}

	{"p-51mustang_ai"
		{vehicle_view "airborne"}
	}	
		
	{"us-p-40"
		{vehicle_view "yak1_ser69"}
	}
	
	{"us-p-40_ai"
		{vehicle_view "yak1_ser69"}
	}

	{"us-b25"
		{vehicle_view "airborne"}
	}
	
	{"us-b25_ai"
		{vehicle_view "airborne"}
	}

	{"f80a_rockets_127x12_ai"
		{vehicle_view "yak1_ser69"}
	}

	{"f80a_mk78x4_ai"
		{vehicle_view "yak1_ser69"}
	}

	{"f80a_450x2_ai"
		{vehicle_view "yak1_ser69"}
	}

	{"p47_d22_recon_ai"
		{vehicle_view "p47_d22"}
	}
	
	{"p47_d22_bomber_ai"
		{vehicle_view "p47_d22"}
	}

	{"p47_d22_m8_ai"
		{vehicle_view "p47_d22"}
	}

	{"p47_d22_hvar_ai"
		{vehicle_view "p47_d22"}
	}

	{"p47_d22_250lb_ai"
		{vehicle_view "p47_d22"}
	}

;==================================================== Modded MISC

	{"inf_eng_crate_ger"
		{vehicle_view "inf_crate_ger"}
	}	
	
	{"inf_eng_crate_rus"
		{vehicle_view "inf_crate_rus"}
	}
	
	{"inf_eng_crate_usa"
		{vehicle_view "inf_crate_usa"}
	}	


;==================================================== Modded ENG
;---------------------------------------------------- Modded ENG Tanks
;---------------------------------------------------- Modded ENG Aircraft

	{"blenheim_mk1_eng_ai"
		{vehicle_view "blenheim_mk1_eng"}
	}

	{"blenheim_mk1_eng_recon_ai"
		{vehicle_view "blenheim_mk1_eng"}
	}

	{"hurribomber_mk2c_ai"
		{vehicle_view "hurricane_mk2c"}
	}

	{"hurricane_mk1a_ai"
		{vehicle_view "hurricane_mk1a"}
	}

	{"typhoon_mk1b_ai"
		{vehicle_view "typhoon_mk1b"}
	}

	{"typhoon_mk1b_recon_ai"
		{vehicle_view "typhoon_mk1b"}
	}

;==================================================== Modded MISC
	
;===================================================== /ARM END