; Vehicle view Definitions for new stat-units

;===================================================== ARM BEGIN	
;----------------------------------------------------- ARM static 

			{"dt_tripod_stand"
				{vehicle_view "m2_30cal_tripod"}
			}

			{"mg42_tripod_stand"
				{vehicle_view "m2_30cal_tripod"}
			}

			{"mg34_tripod_stand"
				{vehicle_view "m2_30cal_tripod"}
			}

			{"dp_tripod_stand"
				{vehicle_view "m2_30cal_tripod"}
			}

			{"76mm_m1938_stand"
				{vehicle_view "52k"}
			}

			{"100mm_bs3_stand"
				{vehicle_view "cannon_100mm_bs3"}
			}

			{"flak38_stand"
				{vehicle_view "flak38"}
			}
							
			{"57mm_m1_late_stand"
				{vehicle_view "cannon_57mm_m1"}
			}
			
			{"57mm_m1_bot"
				{vehicle_view "cannon_57mm_m1"}
			}

			{"75mm_pak9738_late_stand"
				{vehicle_view "cannon_75mm_pak9738"}
			}

			{"105mm_flak38_stand"
				{vehicle_view "flak18"}
			}

			{"ds39_fin_stand"
				{vehicle_view "cannon_ds39_stand_fin"}
			}
					
			{"20mm_itk35_stand"
				{vehicle_view "cannon_20mm_itk35"}
			}
					
			{"75mm_itk37_stand"
				{vehicle_view "cannon_75mm_itk37_stat"}
			}
					
			{"stalinetz60_stand"
				{vehicle_view "stalinetz60"}
			}
					
			{"20mm_itk40_stand"
				{vehicle_view "cannon_20mm_itk40"}
			}
					
			{"75mm_itk37_stand"
				{vehicle_view "cannon_75mm_itk37"}
			}
					
			{"75mm_itk44_stand"
				{vehicle_view "cannon_75mm_itk37"}
			}
					
			{"105mm_k34_stand"
				{vehicle_view "cannon_105mm_k34"}
			}
					
			{"120mm_krh40_stand"
				{vehicle_view "cannon_120mm_krh40"}
			}
					
			{"37mm_flak37_stand"
				{vehicle_view "cannon_37mm_flak37"}
			}
					
			{"50mm_flak41_stand"
				{vehicle_view "cannon_50mm_flak41"}
			}
					
			{"80mm_sgrw34_stand"
				{vehicle_view "mortar_ger"}
			}
					
			{"88mm_flak18_stand"
				{vehicle_view "flak18"}
			}
			
			{"88mm_flak18_bot"
				{vehicle_view "flak18"}
			}
					
			{"105mm_lefh18_stand"
				{vehicle_view "cannon_105mm_lefh18"}
			}
					
			{"120mm_sgrw42_stand"
				{vehicle_view "cannon_120mm_sgrw42"}
			}
				
			{"kpv_1944_dzot"
				{vehicle_view "cannon_dshk_aa"}
			}
					
			{"37mm_61k_stand"
				{vehicle_view "cannon_37mm_61k"}
			}
					
			{"85mm_52k_stand"
				{vehicle_view "52k"}
			}
			
			{"85mm_52k_bot"
				{vehicle_view "52k"}
			}
					
			{"120mm_pm38_stand"
				{vehicle_view "cannon_120mm_pm38"}
			}
					
			{"122mm_m30_stand"
				{vehicle_view "cannon_122mm_m30"}
			}
					
			{"122mm_m1910_stand"
				{vehicle_view "cannon_122mm_m1910"}
			}
					
			{"203mm_b4_stand"
				{vehicle_view "b4"}
			}
					
			{"dshk_aa_stand"
				{vehicle_view "cannon_dshk_aa"}
			}
					
			{"maxim_x4_stand"
				{vehicle_view "cannon_maxim_x4"}
			}
					
			{"ford_3ton_ammo_stand"
				{vehicle_view "fordV3000"}
			}
					
			{"ford_3ton_eng_stand"
				{vehicle_view "fordV3000"}
			}
					
			{"ford_3ton_fuel_stand"
				{vehicle_view "fordV3000"}
			}
					
			{"blitz3_6_engineering_stand"
				{vehicle_view "car"}
			}
					
			{"blitz3_6_fuel_stand"
				{vehicle_view "car"}
			}
					
			{"blitz3_6_radio_stand"
				{vehicle_view "car"}
			}
					
			{"kettenkrad_stand"
				{vehicle_view "kettenkrad"}
			}
					
			{"opel_maultier_stand"
				{vehicle_view "opel_maultier"}
			}
					
			{"gaz_aaa_supply_stand"
				{vehicle_view "gaz"}
			}
					
			{"gaz_fuel_stand"
				{vehicle_view "gaz"}
			}
					
			{"zis5eng_stand"
				{vehicle_view "zis5"}
			}
					
			{"150mm_sw34_stand"
				{vehicle_view "special_150mm_sw34"}
			}
					
			{"inf_crate_ger_stand"
				{vehicle_view "box"}
			}
					
			{"inf_crate_rus_stand"
				{vehicle_view "box"}
			}
					
			{"inf_crate_stand"
				{vehicle_view "box"}
			}
					
			{"ammo_trailer_stand"
				{vehicle_view "ammo_trailer"}
			}
					
			{"107mm_m1910_30_stand"
				{vehicle_view "cannon_107mm_m1910_30"}
			}
					
			{"browning_m2_lafette2_stand"
				{vehicle_view "cannon_dshk_aa"}
			}
					
			{"panzernest_krab_stand"
				{vehicle_view "panzernest_krab"}
			}

			{"40mm_itk38b_stand"
				{vehicle_view "cannon_40mm_itk38b"}
			}
					
			{"105mm_m2a1_stand"
				{vehicle_view "cannon_105mm_m2a1"}
			}
					
			{"mg42_lafette_tower_stand"
				{vehicle_view "mg_stand"}
			}
					
			{"mg34_lafette_tower_stand"
				{vehicle_view "mg_stand"}
			}
					
			{"m2_30cal_tower_stand"
				{vehicle_view "m2_30cal_tripod"}
			}
					
			{"maxim_tower_stand"
				{vehicle_view "mg_maxim"}
			}					
					
			{"maxim_tower_fin_stand"
				{vehicle_view "mg_maxim"}
			}		

			{"81mm_m1_stand"
				{vehicle_view "cannon_81mm_m1"}
			}					

			{"203mm_m1_stand"
				{vehicle_view "cannon_203mm_m1"}
			}	
					
			{"inf_crate_usa_stand"
				{vehicle_view "box"}
			}
					
			{"50calM2_lafette_stand"
				{vehicle_view "cannon_dshk_aa"}
			}
					
			{"90mm_m1a1_stand"
				{vehicle_view "cannon_90mm_m1a1"}
			}
					
			{"75mm_pak40_stand"
				{vehicle_view "cannon_75mm_pak40"}
			}
					
			{"cckw_engineer_late_stand"
				{vehicle_view "cckw_engineer_late"}
			}
									
			{"cckw_fuel_stand"
				{vehicle_view "cckw_fuel"}
			}		

			{"cckw_redball_stand"
				{vehicle_view "cckw_redball"}
			}

			{"inf_crate_usa_stand"
				{vehicle_view "box"}
			}	
					
			{"40mm_m1_stand"
				{vehicle_view "cannon_40mm_m1"}
			}
					
			{"50mm_flak41_bunker_stand"
				{vehicle_view "cannon_50mm_flak41"}
			}
					
			{"50mm_krh38_stand"
				{vehicle_view "cannon_50mm_krh38"}
			}
					
			{"155mm_h17_stand"
				{vehicle_view "cannon_155mm_h17"}
			}
					
			{"150mm_rkh41_stand"
				{vehicle_view "cannon_150mm_nebelwerfer41"}
			}
					
			{"300mm_m30_stand"
				{vehicle_view "300mm_m30"}
			}
					
			{"inf_eng_crate_usa"
				{vehicle_view "box"}
			}
					
			{"inf_eng_crate_ger"
				{vehicle_view "box"}
			}
			
			{"inf_eng_crate_rus"
				{vehicle_view "box"}
			}
					
			{"mg131_lafette_big_stand"
				{vehicle_view "mg_stand"}
			}
					
			{"mg131_lafette_stand"
				{vehicle_view "mg_stand"}
			}
			
			{"mg131_lafette_ger_bunker_stand"
				{vehicle_view "mg_stand"}
			}
			
			{"75mm_itk37_stat"
				{vehicle_view "105mm_flak38_stat"}
			}
			
			{"75mm_itk37_bot"
				{vehicle_view "105mm_flak38_stat"}
			}
			
			{"105mm_flak38_stat"
				{vehicle_view "cannon_75mm_itk37_stat"}
			}
			
			{"cckw_art_ammo_stand"
				{vehicle_view "cckw_art_ammo"}
			}
			
			{"76mm_itk31_stand"
				{vehicle_view "cannon_75mm_itk37"}
			}
			

;----------------------------------------------------- /ARM static 					
;===================================================== /ARM END