;Created by Nikral晓杉同学
;Modify by MaxDrechsler
;Add tags for aa units

; {"muzzle_20mm_25mm_auto"
; 	{on spawn
; 		{delay 0.1
; 			{tags add "aa"}
; 		}
; 	}
; }
; {"muzzle_37mm_40mm_auto"
; 	{on spawn
; 		{delay 0.1
; 			{tags add "aa"}
; 		}
; 	}
; }
; {"automatic"
; 	{on spawn
; 		{delay 0.1
; 			{tags add "aa"}
; 		}
; 	}
; }
; {"muzzle_hmg_dshk"
; 	{on spawn
; 		{delay 0.1
; 			{tags add "aa"}
; 		}
; 	}
; }
; {"muzzle_37mm_40mm_auto_sides"
; 	{on spawn
; 		{delay 0.1
; 			{tags add "aa"}
; 		}
; 	}
; }
; {"flak" ; wirbelwind
; 	{on spawn
; 		{delay 0.1
; 			{tags add "aa"}
; 		}
; 	}
; }
; {"muzzle_hmg_m2hb"
; 	{on spawn
; 		{delay 0.1
; 			{tags add "aa"}
; 		}
; 	}
; }
; {"muzzle_hmg"
; 	{on spawn
; 		{delay 0.1
; 			{tags add "aa"}
; 		}
; 	}
; }
{"c_aa_hvy" ; Heavy AA cannon
	{on spawn
		{delay 0.1
			{tags add "aa"}
		}
	}
}

{"c_aa_med" ; Heavy AA cannon
	{on spawn
		{delay 0.1
			{tags add "aa"}
		}
	}
}

{"c_aa_lite" ; lite AA cannon
	{on spawn
		{delay 0.1
			{tags add "aa"}
		}
	}
}

{"panzer1" ; panzer 1b, 1f
	{on spawn
		{delay 0.1
			{tags add "aa"}
		}
	}
}

;{"detect_cannon_aa"
;		{on spawn
;			{delay 0.1
;				{tags add "aa"}
;		    }
;  	}
;}

{"aa" ;'aa' is a new prop defined by Nikral. It contains all heavy AA guns, wirbelwind, and the Maxim*4.
	{on spawn
		{delay 0.1
			{tags add "aa"}
		}
	}
}