;; ///////////////////////////// SMALL ARMS ///////////////////////////////////////////////////////////////////////
;			///////////////// RUS Weapon Defines ///////////////// 
(define "DShK38"
	{link_sound			"HMG_action_recoil"		"weapon/action/recoil/open_bolt_mg/reciprocating/"}
	{link_sound			"HMG_tail_close" 		"weapon/shot/smallarms/s4/d1/USA/M2HB/Tail/"}
	{link_sound			"HMG_head_mid" 			"weapon/shot/smallarms/s4/d2/USA/M2HB/Head/"}
	{link_sound			"HMG_tail_mid" 			"weapon/shot/smallarms/s4/d2/USA/M2HB/Tail/"}
	{link_sound			"HMG_head_far" 			"weapon/shot/smallarms/s4/d3/RUS/DShK38/Head/"}
	{link_sound			"HMG_tail_far" 			"weapon/shot/smallarms/s4/d3/RUS/DShK38/Tail/"}
)

(define "DShK38_int"
	{link_sound			"HMG_tail_close" 		"weapon/shot/smallarms/s4/d1/USA/M2HB/Tail/"}
	{link_sound			"HMG_head_mid" 			"weapon/shot/smallarms/s4/d2/USA/M2HB/Head/"}
	{link_sound			"HMG_tail_mid" 			"weapon/shot/smallarms/s4/d2/USA/M2HB/Tail/"}
	{link_sound			"HMG_head_far" 			"weapon/shot/smallarms/s4/d3/RUS/DShK38/Head/"}
	{link_sound			"HMG_tail_far" 			"weapon/shot/smallarms/s4/d3/RUS/DShK38/Tail/"}
)

(define "DS39"
	{link_sound 		"action_recoil"			"weapon/action/recoil/open_bolt_mg/"}
	{link_sound			"tail_close" 			"weapon/shot/smallarms/s3/d1/RUS/DS39/Tail/"}
	{link_sound			"head_mid" 				"weapon/shot/smallarms/s3/d2/RUS/DS39/Head/"}
	{link_sound			"tail_mid" 				"weapon/shot/smallarms/s3/d2/RUS/DS39/Tail/"}
	{link_sound			"head_far" 				"weapon/shot/smallarms/s3/d3/RUS/DS39/Head/"}
	{link_sound			"tail_far" 				"weapon/shot/smallarms/s3/d3/RUS/DS39/Tail/"}
)

(define "DT"
	{link_sound 		"Tail_Close"			"weapon/shot/smallarms/s3/d1/rus/dp27/tail/"}
	{link_sound 		"Head_Mid"				"weapon/shot/smallarms/s3/d2/rus/dp27/head/"}
	{link_sound 		"Tail_Mid"				"weapon/shot/smallarms/s3/d2/rus/dp27/tail/"}
	{link_sound 		"Head_Far"				"weapon/shot/smallarms/s3/d3/rus/dp27/head/"}
	{link_sound 		"Tail_Far"				"weapon/shot/smallarms/s3/d3/rus/dp27/tail/"}
)

(define "PM1910_30"
	{link_sound			"tail_close" 			"weapon/shot/smallarms/s3/d1/RUS/PM1910_30/Tail/"}
	{link_sound			"head_mid" 				"weapon/shot/smallarms/s3/d2/RUS/PM1910_30/Head/"}
	{link_sound			"tail_mid" 				"weapon/shot/smallarms/s3/d2/RUS/PM1910_30/Tail/"}
	{link_sound			"head_far" 				"weapon/shot/smallarms/s3/d3/RUS/PM1910_30/Head/"}
	{link_sound			"tail_far" 				"weapon/shot/smallarms/s3/d3/RUS/PM1910_30/Tail/"}
)

(define "PM1910_30_MG1"
	{link_sound			"MG1_tail_close" 			"weapon/shot/smallarms/s3/d1/RUS/PM1910_30/Tail/"}
	{link_sound			"MG1_head_mid" 				"weapon/shot/smallarms/s3/d2/RUS/PM1910_30/Head/"}
	{link_sound			"MG1_tail_mid" 				"weapon/shot/smallarms/s3/d2/RUS/PM1910_30/Tail/"}
	{link_sound			"MG1_head_far" 				"weapon/shot/smallarms/s3/d3/RUS/PM1910_30/Head/"}
	{link_sound			"MG1_tail_far" 				"weapon/shot/smallarms/s3/d3/RUS/PM1910_30/Tail/"}
)

(define "SG43"
	{link_sound 		"action_recoil"			"weapon/action/recoil/open_bolt_mg/"}
	{link_sound			"tail_close" 			"weapon/shot/smallarms/s3/d1/RUS/SG43/Tail/"}
	{link_sound			"head_mid" 				"weapon/shot/smallarms/s3/d2/RUS/SG43/Head/"}
	{link_sound			"tail_mid" 				"weapon/shot/smallarms/s3/d2/RUS/SG43/Tail/"}
	{link_sound			"head_far" 				"weapon/shot/smallarms/s3/d3/RUS/SG43/Head/"}
	{link_sound			"tail_far" 				"weapon/shot/smallarms/s3/d3/RUS/SG43/Tail/"}
)

(define "ZPU_1931_4M"
	{link_sound 		"MultiBarrel_action_recoil"			"weapon/action/recoil/open_bolt_mg/reciprocating/"}
	{link_sound			"MultiBarrel_tail_close" 			"weapon/shot/smallarms/s3/d1/RUS/PM1910_30/ZPU_1931_4M/Tail/"}
	{link_sound			"MultiBarrel_head_mid" 				"weapon/shot/smallarms/s3/d2/RUS/PM1910_30/ZPU_1931_4M/Head/"}
	{link_sound			"MultiBarrel_tail_mid" 				"weapon/shot/smallarms/s3/d2/RUS/PM1910_30/ZPU_1931_4M/Tail/"}
	{link_sound			"MultiBarrel_head_far" 				"weapon/shot/smallarms/s3/d3/RUS/PM1910_30/ZPU_1931_4M/Head/"}
	{link_sound			"MultiBarrel_tail_far" 				"weapon/shot/smallarms/s3/d3/RUS/PM1910_30/ZPU_1931_4M/Tail/"}
)
;			///////////////// GER Weapon Defines ///////////////// 

(define "MG08"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/ger/mg08/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/ger/mg08/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/ger/mg08/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/ger/mg08/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/ger/mg08/tail/"}
)

(define "MG13"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/ger/mg13/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/ger/mg13/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/ger/mg13/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/ger/mg13/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/ger/mg13/tail/"}
)

(define "MG15"
	{link_sound			"MG4_Tail_Close"		"weapon/shot/smallarms/s3/d1/ger/mg15/tail/"}
	{link_sound			"MG4_Head_Mid"			"weapon/shot/smallarms/s3/d2/ger/mg15/head/"}
	{link_sound			"MG4_Tail_Mid"			"weapon/shot/smallarms/s3/d2/ger/mg15/tail/"}
	{link_sound			"MG4_Head_Far"			"weapon/shot/smallarms/s3/d3/ger/mg15/head/"}
	{link_sound			"MG4_Tail_Far"			"weapon/shot/smallarms/s3/d3/ger/mg15/tail/"}
)

(define "MG17"
	{link_sound			"MG2_Tail_Close"		"weapon/shot/smallarms/s3/d1/ger/mg17/tail/"}
	{link_sound			"MG2_Head_Mid"			"weapon/shot/smallarms/s3/d2/ger/mg17/head/"}
	{link_sound			"MG2_Tail_Mid"			"weapon/shot/smallarms/s3/d2/ger/mg17/tail/"}
	{link_sound			"MG2_Head_Far"			"weapon/shot/smallarms/s3/d3/ger/mg17/head/"}
	{link_sound			"MG2_Tail_Far"			"weapon/shot/smallarms/s3/d3/ger/mg17/tail/"}
)

(define "MG34"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/ger/mg34/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/ger/mg34/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/ger/mg34/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/ger/mg34/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/ger/mg34/tail/"}
)

(define "MG42"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/ger/mg42/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/ger/mg42/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/ger/mg42/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/ger/mg42/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/ger/mg42/tail/"}
)
(define "MG131"
	{link_sound			"HMG_tail_close" 		"weapon/shot/smallarms/s4/d1/GER/MG151_15/Drilling/Tail/"}
	{link_sound			"HMG_head_mid"			"weapon/shot/smallarms/s4/d2/GER/MG151_15/Drilling/Head/"}
	{link_sound			"HMG_tail_mid"			"weapon/shot/smallarms/s4/d2/GER/MG151_15/Drilling/Tail/"}
	{link_sound			"HMG_head_far"			"weapon/shot/smallarms/s4/d3/GER/MG151_15/Drilling/Head/"}
	{link_sound			"HMG_tail_far"			"weapon/shot/smallarms/s4/d3/GER/MG151_15/Drilling/Tail/"}
)
(define "MG151_15_Drilling"
	{link_sound			"MultiBarrel_action_recoil" 		"weapon/shot/smallarms/s4/recoil/GER/MG151_15/"}
	{link_sound			"MultiBarrel_tail_close" 			"weapon/shot/smallarms/s4/d1/GER/MG151_15/Drilling/Tail/"}
	{link_sound			"MultiBarrel_head_mid"				"weapon/shot/smallarms/s4/d2/GER/MG151_15/Drilling/Head/"}
	{link_sound			"MultiBarrel_tail_mid"				"weapon/shot/smallarms/s4/d2/GER/MG151_15/Drilling/Tail/"}
	{link_sound			"MultiBarrel_head_far"				"weapon/shot/smallarms/s4/d3/GER/MG151_15/Drilling/Head/"}
	{link_sound			"MultiBarrel_tail_far"				"weapon/shot/smallarms/s4/d3/GER/MG151_15/Drilling/Tail/"}
)

;			///////////////// FIN Weapon Defines ///////////////// 

(define "LS26"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/FIN/LS26/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/FIN/LS26/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/FIN/LS26/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/FIN/LS26/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/FIN/LS26/tail/"}
)

(define "KP31"
	{link_sound			"SMG_Tail_Close"		"weapon/shot/smallarms/s1/d1/fin/kp31/tail/"}
	{link_sound			"SMG_Head_Mid"			"weapon/shot/smallarms/s1/d2/fin/kp31/head/"}
	{link_sound			"SMG_Tail_Mid"			"weapon/shot/smallarms/s1/d2/fin/kp31/tail/"}
	{link_sound			"SMG_Head_Far"			"weapon/shot/smallarms/s1/d3/fin/kp31/head/"}
	{link_sound			"SMG_Tail_Far"			"weapon/shot/smallarms/s1/d3/fin/kp31/tail/"}
)

;			///////////////// USA Weapon Defines ///////////////// 

(define "M1919A4"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/USA/M1919A4/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/USA/M1919A4/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/USA/M1919A4/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/USA/M1919A4/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/USA/M1919A4/tail/"}
)

(define "M2HB"
	{link_sound			"HMG_action_recoil"		"weapon/action/recoil/closed_bolt_HMG/"}
	{link_sound			"HMG_tail_close" 		"weapon/shot/smallarms/s4/d1/USA/M2HB/Tail/"}
	{link_sound			"HMG_head_mid" 			"weapon/shot/smallarms/s4/d2/USA/M2HB/Head/"}
	{link_sound			"HMG_tail_mid" 			"weapon/shot/smallarms/s4/d2/USA/M2HB/Tail/"}
	{link_sound			"HMG_head_far" 			"weapon/shot/smallarms/s4/d3/RUS/DShK38/Head/"}
	{link_sound			"HMG_tail_far" 			"weapon/shot/smallarms/s4/d3/RUS/DShK38/Tail/"}
)

(define "M33_DualMount"
	{link_sound			"MultiBarrel_action_recoil"			"weapon/action/recoil/closed_bolt_HMG/"}
	{link_sound			"MultiBarrel_tail_close" 			"weapon/shot/smallarms/s4/d1/USA/M2HB/Gun_Mounts/M33_DualMount_Tail/"}
	{link_sound			"MultiBarrel_head_mid" 				"weapon/shot/smallarms/s4/d2/USA/M2HB/Gun_Mounts/M33_DualMount_Head/"}
	{link_sound			"MultiBarrel_tail_mid" 				"weapon/shot/smallarms/s4/d2/USA/M2HB/Gun_Mounts/M33_DualMount_Tail/"}
	{link_sound			"MultiBarrel_head_far" 				"weapon/shot/smallarms/s4/d3/USA/M2HB/Gun_Mounts/M33_DualMount_Head/"}
	{link_sound			"MultiBarrel_tail_far" 				"weapon/shot/smallarms/s4/d3/USA/M2HB/Gun_Mounts/M33_DualMount_Tail/"}
)

(define "M45_QuadMount"
	{link_sound			"MultiBarrel_action_recoil"			"weapon/action/recoil/closed_bolt_HMG/"}
	{link_sound			"MultiBarrel_tail_close" 			"weapon/shot/smallarms/s4/d1/USA/M2HB/Gun_Mounts/M45_QuadMount_Tail/"}
	{link_sound			"MultiBarrel_head_mid" 				"weapon/shot/smallarms/s4/d2/USA/M2HB/Gun_Mounts/M45_QuadMount_Head/"}
	{link_sound			"MultiBarrel_tail_mid" 				"weapon/shot/smallarms/s4/d2/USA/M2HB/Gun_Mounts/M45_QuadMount_Tail/"}
	{link_sound			"MultiBarrel_head_far" 				"weapon/shot/smallarms/s4/d3/USA/M2HB/Gun_Mounts/M45_QuadMount_Head/"}
	{link_sound			"MultiBarrel_tail_far" 				"weapon/shot/smallarms/s4/d3/USA/M2HB/Gun_Mounts/M45_QuadMount_Tail/"}
)

;			///////////////// ENG Weapon Defines ///////////////// 

(define "Bren"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/ENG/BREN_Gun/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/ENG/BREN_Gun/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/ENG/BREN_Gun/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/ENG/BREN_Gun/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/ENG/BREN_Gun/tail/"}
)

(define "Browning_303_x8"
	{link_sound		"head_loop_close" 	"weapon/shot/smallarms/s3/d1/ENG/Browning_303/"}
	{link_sound		"tail_close" 		"weapon/shot/smallarms/s3/d1/ENG/Browning_303/Tails/"}
	{link_sound		"head_loop_mid"		"weapon/shot/smallarms/s3/d2/ENG/Browning_303/"}
	{link_sound		"tail_mid"		"weapon/shot/smallarms/s3/d2/ENG/Browning_303/Tails/"}
	{link_sound		"head_loop_far"		"weapon/shot/smallarms/s3/d3/ENG/Browning_303/"}
	{link_sound		"tail_far"		"weapon/shot/smallarms/s3/d3/ENG/Browning_303/Tails/"}
)

(define "Vickers"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/ENG/Vickers/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/ENG/Vickers/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/ENG/Vickers/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/ENG/Vickers/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/ENG/Vickers/tail/"}
)

(define "Vickers_GO"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/ENG/Vickers_GO/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/ENG/Vickers_GO/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/ENG/Vickers_GO/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/ENG/Vickers_GO/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/ENG/Vickers_GO/tail/"}
)

(define "Vickers_50"
	{link_sound			"HMG_tail_close" 		"weapon/shot/smallarms/s4/d1/ENG/Vickers_50/Tail/"}
	{link_sound			"HMG_head_mid" 			"weapon/shot/smallarms/s4/d2/ENG/Vickers_50/Head/"}
	{link_sound			"HMG_tail_mid" 			"weapon/shot/smallarms/s4/d2/ENG/Vickers_50/Tail/"}
	{link_sound			"HMG_head_far" 			"weapon/shot/smallarms/s4/d3/RUS/DShK38/Head/"}
	{link_sound			"HMG_tail_far" 			"weapon/shot/smallarms/s4/d3/RUS/DShK38/Tail/"}
)

;			///////////////// Shared Weapon Defines ///////////////// 

(define "MAC31"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/Shared/MAC1931/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/Shared/MAC1931/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/Shared/MAC1931/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/Shared/MAC1931/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/Shared/MAC1931/tail/"}
)

(define "ZB37"
	{link_sound			"Tail_Close"			"weapon/shot/smallarms/s3/d1/Shared/ZB37/tail/"}
	{link_sound			"Head_Mid"				"weapon/shot/smallarms/s3/d2/Shared/ZB37/head/"}
	{link_sound			"Tail_Mid"				"weapon/shot/smallarms/s3/d2/Shared/ZB37/tail/"}
	{link_sound			"Head_Far"				"weapon/shot/smallarms/s3/d3/Shared/ZB37/head/"}
	{link_sound			"Tail_Far"				"weapon/shot/smallarms/s3/d3/Shared/ZB37/tail/"}
)

(define "ZB37_QuadMount"
	{link_sound			"MG1_tail_close" 		"weapon/shot/smallarms/s3/d1/Shared/ZB37/QuadMount/Tail/"}
	{link_sound			"MG1_head_mid" 			"weapon/shot/smallarms/s3/d2/Shared/ZB37/QuadMount/Head/"}
	{link_sound			"MG1_tail_mid" 			"weapon/shot/smallarms/s3/d2/Shared/ZB37/QuadMount/Tail/"}
	{link_sound			"MG1_head_far" 			"weapon/shot/smallarms/s3/d3/Shared/ZB37/QuadMount/Head/"}
	{link_sound			"MG1_tail_far" 			"weapon/shot/smallarms/s3/d3/Shared/ZB37/QuadMount/Tail/"}
)

(define "Automatic_Weapon"
	; Granular Head – played on EVERY shot
	{play_sound "action_recoil"}
	{play_sound "head_mid"}
	{play_sound "head_far"}
	{tags add "firing"}
	{kill_delay "burst_end"}

	{delay 0.001 "burst_end"
		{tags remove "firing"}
		; Tail – plays only when the burst is complete
		{play_sound "tail_close"}
		{play_sound "tail_mid"}
		{play_sound "tail_far"}
	}
)

(define "Automatic_Weapon_Space"
	{play_sound "%weapon_head_mid"}
	{play_sound "%weapon_head_far"}
	{tags add "firing"}
	{kill_delay "burst_end"}
	{delay 0.001 "burst_end"
		{tags remove "firing"}
		{play_sound "%weapon_tail_close"}
		{play_sound "%weapon_tail_mid"}
		{play_sound "%weapon_tail_far"}
	}
)

(define "multi_barrel_loop"
	{on "init_gun"
		{add_view "%flash"		"flashbarrel00"	"shooter00"}
		{add_view "%flash"		"flashbarrel01"	"shooter01"}
		{add_view "%flash"		"flashbarrel02"	"shooter02"}
		{add_view "%flash"		"flashbarrel03"	"shooter03"}
		{add_view "%flash"		"flashbarrel04"	"shooter04"}
		{add_view "%flash"		"flashbarrel05"	"shooter05"}
		{add_view "%flash"		"flashbarrel06"	"shooter06"}
		{add_view "%flash"		"flashbarrel07"	"shooter07"}
		{add_view "%smoke"		"smoke00"		"FXshell1"}
		{add_view "%smoke"		"smoke01"		"FXshell2"}
		{add_view "%smoke"		"smoke02"		"FXshell3"}
		{add_view "%smoke"		"smoke03"		"FXshell4"}
		{add_view "%smoke"		"smoke04"		"FXshell5"}
		{add_view "%smoke"		"smoke05"		"FXshell6"}
		{add_view "%smoke"		"smoke06"		"FXshell7"}
		{add_view "%smoke"		"smoke07"		"FXshell8"}
		{add_view "%shell"		"shell00"		"FXshell1"}
		{add_view "%shell"		"shell01"		"FXshell2"}
		{add_view "%shell"		"shell02"		"FXshell3"}
		{add_view "%shell"		"shell03"		"FXshell4"}
		{add_view "%shell"		"shell04"		"FXshell5"}
		{add_view "%shell"		"shell05"		"FXshell6"}
		{add_view "%shell"		"shell06"		"FXshell7"}
		{add_view "%shell"		"shell07"		"FXshell8"}

		{link_sound "rotate_turret" 	"vehicle/turret/gun/gun_horizontal"}
		{link_sound "rotate_gun" 		"vehicle/turret/gun/gun_vertical"}
		{call "update_gun"}
	}

	{on fire "%weapon" overload
		{play_sound "MultiBarrel_action_recoil"}
		{play_sound "MultiBarrel_head_mid"}
		{play_sound "MultiBarrel_head_far"}
		{tags add "firing"}
		{delay 0.001
			{tags remove "firing"}
			{play_sound "MultiBarrel_tail_close"}
			{play_sound "MultiBarrel_tail_mid"}
			{play_sound "MultiBarrel_tail_far"}
		}
		(define "fire_barrel"
			name "%0"
				{call "fire_barrel%0"}
				{view show "flashbarrel%0"}
				{view start "flashbarrel%0"}
				{ani_play "fire%0"}
				{view start "shell%0"}
				{view start "smoke%0"}
				{delay 0.12 "shell_off"
					{view pause "shell%0"}
					{view pause "smoke%0"}
				}
				{delay 0.2 "fire"
					{view hide	"flashbarrel%0"}
					{view pause	"flashbarrel%0"}
				}
		)
		{if	("fire_barrel" args 00)
		else ("fire_barrel" args 01)
		else ("fire_barrel" args 02)
		else ("fire_barrel" args 03)
		else ("fire_barrel" args 04)
		else ("fire_barrel" args 05)
		else ("fire_barrel" args 06)
		else ("fire_barrel" args 07)
		}
	}
)

;; ///////////////////////////// CANNONS ///////////////////////////////////////////////////////////////////////
;----------------------------------------------- SIZE 1 -------------------------------------------------------------------//
(define "Autocannon_s1"
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/Shared/Autocannon_20to30mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/Shared/Autocannon_20to30mm/"}
)

(define "Autocannon_s1_Rapid"
	{link_sound		"action_recoil_Cannon"			"weapon/shot/cannon/s1/recoil/Shared/Autocannon_20to30mm/"}
	{link_sound		"Cannon_tail_close" 			"weapon/shot/cannon/s1/d1/Shared/Autocannon_20to30mm/Multi_Barrel/Tail/"}
	{link_sound		"Cannon_head_mid"				"weapon/shot/cannon/s1/d2/Shared/Autocannon_20to30mm/Multi_Barrel/Head/"}
	{link_sound		"Cannon_tail_mid"				"weapon/shot/cannon/s1/d2/Shared/Autocannon_20to30mm/Multi_Barrel/Tail/"}
	{link_sound		"Cannon_head_far"				"weapon/shot/cannon/s1/d3/Shared/Autocannon_20to30mm/Multi_Barrel/Head/"}
	{link_sound		"Cannon_tail_far"				"weapon/shot/cannon/s1/d3/Shared/Autocannon_20to30mm/Multi_Barrel/Tail/"}
)

(define "Autocannon_s1_MultiBarrel"
	{link_sound		"MultiBarrel_action_recoil"		"weapon/shot/cannon/s1/recoil/Shared/Autocannon_20to30mm/"}
	{link_sound		"MultiBarrel_tail_close" 		"weapon/shot/cannon/s1/d1/Shared/Autocannon_20to30mm/Multi_Barrel/Tail/"}
	{link_sound		"MultiBarrel_head_mid"			"weapon/shot/cannon/s1/d2/Shared/Autocannon_20to30mm/Multi_Barrel/Head/"}
	{link_sound		"MultiBarrel_tail_mid"			"weapon/shot/cannon/s1/d2/Shared/Autocannon_20to30mm/Multi_Barrel/Tail/"}
	{link_sound		"MultiBarrel_head_far"			"weapon/shot/cannon/s1/d3/Shared/Autocannon_20to30mm/Multi_Barrel/Head/"}
	{link_sound		"MultiBarrel_tail_far"			"weapon/shot/cannon/s1/d3/Shared/Autocannon_20to30mm/Multi_Barrel/Tail/"}
)
(define "Autocannon_s2"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/Shared/Autocannon_37to40mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/Shared/Autocannon_37to40mm/"}
)
(define "Cannon_37to40mm"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/Shared/Cannon_37to40mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/Shared/Cannon_37to40mm/"}
)
(define "Mortar_5-6cm"
	{link_sound		"Recoil"		"weapon/shot/cannon/s1/recoil/Shared/Mortar/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s1/d2/Shared/Mortar/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s1/d3/Shared/Mortar/"}
)
(define "Cannon_Breech"
	{link_sound		"breech_open"		"weapon/reload/tank/breech_open/"}
	{link_sound		"breech_close"		"weapon/reload/tank/breech_close/"}
)
;----------------------------------------------- SIZE 2 -------------------------------------------------------------------//
(define "Cannon_45to47mm"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s2/d2/Shared/Cannon_45to47mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s2/d3/Shared/Cannon_45to47mm/"}
)
(define "Cannon_50to57mm"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s2/d2/Shared/Cannon_50to57mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s2/d3/Shared/Cannon_50to57mm/"}
)
(define "Cannon_50to57mm_HV"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s2/d2/Shared/Cannon_50to57mm_HV/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s2/d3/Shared/Cannon_50to57mm_HV/"}
)
(define "Mortar_8cm"
	{link_sound		"Recoil"		"weapon/shot/cannon/s2/recoil/Shared/Mortar/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s2/d2/Shared/Mortar/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s2/d3/Shared/Mortar/"}
)
;----------------------------------------------- SIZE 3 -------------------------------------------------------------------//
(define "Cannon_75to76mm"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s3/d2/Shared/Cannon_75to76mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s3/d3/Shared/Cannon_75to76mm/"}
)
(define "Cannon_75to76mm_LV"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s3/d2/Shared/Cannon_75to76mm_LV/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s3/d3/Shared/Cannon_75to76mm_LV/"}
)
(define "Cannon_75to76mm_HV"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s3/d2/Shared/Cannon_75to76mm_HV/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s3/d3/Shared/Cannon_75to76mm_HV/"}
)
(define "Mortar_12cm"
	{link_sound		"Recoil"		"weapon/shot/cannon/s3/recoil/Shared/Mortar/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s3/d2/Shared/Mortar/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s3/d3/Shared/Mortar/"}
)
;----------------------------------------------- SIZE 4 -------------------------------------------------------------------//
(define "Cannon_85to100mm"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_85to100mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_85to100mm/"}
)
(define "Cannon_85to100mm_HV"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_85to100mm_HV/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_85to100mm_HV/"}
)
(define "Cannon_105to130mm"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_105to130mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_105to130mm/"}
)
(define "Cannon_105to130mm_LV"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s4/d2/Shared/Cannon_105to130mm_LV/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s4/d3/Shared/Cannon_105to130mm_LV/"}
)
;----------------------------------------------- SIZE 5 -------------------------------------------------------------------//
(define "Cannon_150to210mm"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s3/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s5/d2/Shared/Cannon_150to210mm/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s5/d3/Shared/Cannon_150to210mm/"}
)
;----------------------------------------------- SIZE 6 -------------------------------------------------------------------//
(define "Cannon_280mm+"
	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s3/recoil/Shared/Cannon/"}
	{link_sound		"Cannon_Mid"		"weapon/shot/cannon/s6/d2/Shared/Cannon_280mm+/"}
	{link_sound		"Cannon_Far"		"weapon/shot/cannon/s6/d3/Shared/Cannon_280mm+/"}
)
;--------------------------------------------ARm
(define "2cm_Flakvierling"

	{link_sound		"action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Autocannon_20to30mm/"}
	{link_sound		"head_loop_close" 		"weapon/shot/cannon/s1/d1/GER/2cm_Flakvierling/Head_Loop/"}
	{link_sound		"tail_close" 		"weapon/shot/cannon/s1/d1/GER/2cm_Flakvierling/Tail/"}
	{link_sound		"head_loop_mid"		"weapon/shot/cannon/s1/d2/GER/2cm_Flakvierling/Head_Loop/"}
	{link_sound		"tail_mid"			"weapon/shot/cannon/s1/d2/GER/2cm_Flakvierling/Tail/"}
	{link_sound		"head_loop_far"		"weapon/shot/cannon/s1/d3/GER/2cm_Flakvierling/Head_Loop/"}
	{link_sound		"tail_far"			"weapon/shot/cannon/s1/d3/GER/2cm_Flakvierling/Tail/"}
)

;--------------------------------------------MACE
(define "KPVT_AA"
	{link_sound 		"action_recoil_HMG"	"weapon/action/recoil/closed_bolt_HMG/"}
	{link_sound			"HMG_Mid"		"weapon/shot/smallarms/s4/d2/RUS/DShK38/"}
	{link_sound 		"HMG_Far"		"weapon/shot/smallarms/s4/d3/RUS/DShK38/"}
)
(define "KPVT"
	{link_sound			"HMG_Mid"		"weapon/shot/smallarms/s4/d2/RUS/DShK38/"}
	{link_sound 		"HMG_Far"		"weapon/shot/smallarms/s4/d3/RUS/DShK38/"}
)
(define "RP_46"
	{link_sound	 		"MG_Mid"		"weapon/shot/smallarms/s3/d2/RUS/DP27/"}
	{link_sound	 		"MG_Far"		"weapon/shot/smallarms/s3/d3/RUS/DP27/"}
)
(define "mg131"
	{link_sound 		"action_recoil_HMG"	"weapon/action/recoil/closed_bolt_HMG/"}
	{link_sound			"HMG_Mid"		"weapon/shot/smallarms/s4/d2/RUS/DShK38/"}
	{link_sound 		"HMG_Far"		"weapon/shot/smallarms/s4/d3/RUS/DShK38/"}
)	

(define "multi_barrel_bazooka"
	{on "init_gun"
		{add_view "%flash"		"flashbarrel00"	"shooter00"}
		{add_view "%flash"		"flashbarrel01"	"shooter01"}
		{add_view "%smoke"		"smoke00"	"fx_shooter00"}
		{add_view "%smoke"		"smoke01"	"fx_shooter01"}
		{call "update_gun"}
	}
	{on fire "%weapon" overload
		(define "fire_barrel"
			name "%0"
				{call "fire_barrel%0"}
				{view start "smoke%0"}
				{view show "flashbarrel%0"}
				{view start "flashbarrel%0"}
		)
		{if	("fire_barrel" args 00)
		else ("fire_barrel" args 01)
		}
	}
)