; File: 		tp_control_arm.inc
; Catalog: 		set
; Created by: 	Max Drechsler
; Created:		x.xx.xxxx
; Modify by:	Max Drechsler
; Modify:		11.09.2026
; DSL:			GEM ENGINE 2 Gates of Hell
; Version:		1.1
; Description: 	Third Person Control Definitions for new units

;========================================================== Modded BEGIN
;------------------------------------ALL

;------------------------------------GER

        {"inf_eng_crate_ger" inherit "vehicle high_mg.common"}		
		{"opel_blitz_omnibus" inherit "vehicle generic.unarmed"}

;//		{"sdkfz_251_21" inherit "vehicle atgun.pak36"}

;//		{"blitz3_6_medic" inherit "vehicle generic.unarmed"}
		{"volvo" inherit "vehicle generic.unarmed"}
		{"volvo_art" inherit "vehicle generic.unarmed"}
		{"sdkfz6_weapon" inherit "vehicle generic.unarmed"}
		{"sdkfz6_supply" inherit "vehicle generic.unarmed"}
		
		{"blitz3_6_raketenwerfer" inherit "vehicle spa.common"}

		{"105mm_flak38" inherit "vehicle atgun.flak18"}
;//		{"vk6501h" inherit "vehicle tank.vk65"}	
		{"vk6501h" inherit "vehicle tank.is_MACE"}		

		{"ba6_roa" inherit "vehicle tank.t26"}
		{"tiger_p" inherit "vehicle tank.tiger2h_3_2"}
		{"zgkw303f" inherit "vehicle artillery.katyusha"}
		{"sdkfz251_20" inherit "vehicle sdkfz251c"}	
		{"sdkfz251d_2xgrw42" inherit "vehicle mortar.common"}		
		{"vk3601h" inherit "vehicle tank.is_MACE"}	
		{"panzer_2j" inherit "vehicle tank.panzer2f"}
;//		{"dicker_max_iva" inherit "vehicle td.marder3m"}
		{"jagdtiger88" inherit "vehicle td.jagdtiger"}

;//		{"stug3a" inherit "vehicle td.stug3b"}
		{"stug4g" inherit "vehicle td.stug4"}

		{"mg34_tripod" inherit "vehicle medium_mg.common"}
		{"mg42_tripod" inherit "vehicle medium_mg.common"}
		{"mg131_lafette" inherit "vehicle lafette.common"}
;//		{"mg131_tripod" inherit "vehicle low_mg.common"}
		{"20mm_kwk30_inf" inherit "vehicle atgun.l39"}
;//		{"solothurn_s18_100" inherit "vehicle atgun.solothurn"}
		
		{"flak38" inherit "vehicle atgun.flak38"}
		{"9cm_flak41i" inherit "vehicle atgun.52k"}
		{"76mm_pak36r" inherit "vehicle atgun.common"}
		{"75mm_pak41" inherit "vehicle atgun.pak40"}

		{"t26_pak9738" inherit "vehicle td.hetzer"}
		{"t26_pak9738_ger" inherit "vehicle td.hetzer"}
		{"t34_kwk37" inherit "vehicle tank.t3457"}
		{"pzkpfw_kw_la753r" inherit "vehicle tank.kv1"}
		{"pzkpfw_kw_la753r_ger" inherit "vehicle tank.kv1"}
		{"pzkw753_40" inherit "vehicle tank.kv1"}
		{"pzkw753_41" inherit "vehicle tank.kv1"}
		{"pzkw755_s" inherit "vehicle tank.kv1s"}		
		{"PzKw747_57_43" inherit "vehicle tank.t3457"}
		{"PzKw747_76_41" inherit "vehicle tank.t3476_41"}
		{"PzKw747_85" inherit "vehicle td.su100y"}
		{"pzkpfw_tiger_h1" inherit "vehicle tank.tigerh"}
;//     {"panzerjager1_b" inherit "vehicle td.panzerjaeger_mace"}	
        {"panzerjager1_b" inherit "vehicle atgun.pak38.mounted"}		
        {"pzvd_pziv_turret" inherit "vehicle tank.panzer4h"}
        {"pzvd_pziv_turret_bare" inherit "vehicle tank.panzer4h"}
;//		{"panther_f" inherit "vehicle tank.panther"}
		{"panther_ii-hd" inherit "vehicle tank.panther_88_MACE"}
;//		{"kv220" inherit "vehicle tank.is_MACE"}	
;//		{"kv_220" inherit "vehicle tank.is_MACE"}		
		{"geschuetzwagen_ivb" inherit "vehicle td.stuh42"}
		{"lowehd" inherit "vehicle tank.tiger1h_mace"}
		
		{"tiger1h_early" inherit "vehicle tank.tiger1h_mace"}

		{"marder139" inherit "vehicle tank.is_MACE"}
		{"marder139_rus" inherit "vehicle tank.is_MACE"}
		{"marder3h" inherit "vehicle tank.is_MACE"}
		
;//		{"m4a4_firefly_ger" inherit "vehicle tank.sherman_76"}

		{"v1t" inherit "vehicle artillery.katyusha"}
		{"v1" inherit "vehicle artillery.katyusha"}	
		{"v2_a4" inherit "vehicle artillery.katyusha"}		

		{"ju-52" inherit "vehicle aircraft.common"}
		{"ju-52_para_plane" inherit "vehicle aircraft.common"}
		{"ju-52_para_plane_player" inherit "vehicle aircraft.common"}

		{"ju-87" inherit "vehicle aircraft.common"}
		{"ju-87_ai" inherit "vehicle aircraft.common"}		
		{"bf109_e4b_ai" inherit "vehicle aircraft.common"}
		{"bf109_f2" inherit "vehicle aircraft.common"}	
		{"bf109_f2_ai" inherit "vehicle aircraft.common"}
		{"bf109_f4_ai" inherit "vehicle aircraft.common"}
		{"bf109_g6_ai" inherit "vehicle aircraft.common"}
		{"bf109_g6_rocket_ai" inherit "vehicle aircraft.common"}
		{"bf110_e2_ai" inherit "vehicle aircraft.common"}
		{"bf110_e2_1000kg_ai" inherit "vehicle aircraft.common"}
		{"bf110_e2_rocket_ai" inherit "vehicle aircraft.common"}
		{"bf110_e2_flam_500kg_ai" inherit "vehicle aircraft.common"}
		{"bf110_f4" inherit "vehicle aircraft.common"}
		{"bf110_f4_ai" inherit "vehicle aircraft.common"}
		{"me-262_a1_new" inherit "vehicle aircraft.common"}
		{"me-262_a1_new_ai" inherit "vehicle aircraft.common"}
		{"me_262_50mm_ai" inherit "vehicle aircraft.common"}
		{"me_262_rockets_210x2_ai" inherit "vehicle aircraft.common"}
		{"ai_fi156" inherit "vehicle aircraft.common"}

;------------------------------------USSR
        {"inf_eng_crate_rus" inherit "vehicle high_mg.common"}		

;//		{"kpv_1944" inherit "vehicle lafette.common"}
		{"kpv_1944" inherit "vehicle medium_mg.common"}
		{"ZP_3154B" inherit "vehicle generic.searchlight"}
		
		{"m72o" inherit "vehicle generic.moto"}

		{"gaz_aaa_open" inherit "vehicle generic.unarmed"}
		{"gaz67_open" inherit "vehicle generic.unarmed"}
		{"zis5_open" inherit "vehicle generic.unarmed"}
		{"zis5_61k" inherit "vehicle truck.gaz72k"}
		{"cckw_ussr" inherit "vehicle generic.unarmed"}

		{"voroshilovets" inherit "vehicle generic.unarmed"}
		{"ba11" inherit "vehicle tank.t26"}
		{"ba64d" inherit "vehicle vehicle.mg"}
		{"m2_halftrack_rus" inherit "vehicle vehicle.m2halftrack"}

		{"125mm_pma40_prot" inherit "vehicle mortar.common"}
		{"82mm_bm37_ai" inherit "vehicle mortar.common"}

		{"su57b" inherit "vehicle tank.valentinemk9"}
		{"su5" inherit "vehicle td.su14_2"}
		{"su14" inherit "vehicle td.su14_2"}

		{"t34_44nohead" inherit "vehicle tank.t3485"}
		{"t34_44supply" inherit "vehicle tank.t3485"}
		
		{"94km" inherit "vehicle truck.gaz72k"}
;//		{"zsu_37" inherit "vehicle atgun.zsu_37"}
		
		{"t3485_43" inherit "vehicle tank.is_MACE"}
		{"it_3" inherit "vehicle tank.t3476early"}
		{"a32_39" inherit "vehicle tank.t3476early"}
		{"t4485" inherit "vehicle tank.t3485_mace"}
;//		{"t44100" inherit "vehicle td.t3485"}
		{"t44100" inherit "vehicle tank.t3485_mace"}											
		{"panther_5" inherit "vehicle tank.panther_MACE_ussr"}

		{"su122p" inherit "vehicle td.isu122"}
		{"su122e" inherit "vehicle td.su122"}
		{"su152_late" inherit "vehicle td.su152"}
		{"wolverine" inherit "vehicle tank.m10_gmc"}

		{"kv-3" inherit "vehicle tank.kv85"}
		{"kv1_122" inherit "vehicle tank.kv1_122"}
		{"kv2_39" inherit "vehicle tank.kv2"}
		{"object248" inherit "vehicle tank.is2"}
		{"is_100" inherit "vehicle tank.is2"}
;//		{"is_4_100" inherit "vehicle tank.is_MACE"}

		{"yak1_ser69_ai" inherit "vehicle aircraft.common"}
		{"il2_mod42_ai" inherit "vehicle aircraft.common"}
		{"il2_mod41" inherit "vehicle aircraft.common"}
		{"il2_mod41_ai" inherit "vehicle aircraft.common"}
		{"li-2" inherit "vehicle aircraft.common"}
		{"rus-b25" inherit "vehicle aircraft.common"}	
		{"rus-b25_ai" inherit "vehicle aircraft.common"}	
		{"ussr-p-39" inherit "vehicle aircraft.common"}
		{"ussr-p-39_ai" inherit "vehicle aircraft.common"}
		{"ai_po2" inherit "vehicle aircraft.common"}
		{"po2_flame" inherit "vehicle aircraft.common"}
		{"po2_rocket" inherit "vehicle aircraft.common"}
		
;------------------------------------FIN
		{"smk_fin" inherit "vehicle tank.smk"}

		{"volvo_weapon" inherit "vehicle generic.unarmed"}
		
		{"po2_fin" inherit "vehicle aircraft.common"}
		{"po2_fin_ai" inherit "vehicle aircraft.common"}	
		{"fokker_fin" inherit "vehicle aircraft.common"}
		{"fokker_fin_ai" inherit "vehicle aircraft.common"}
		{"bf109_g6_fin" inherit "vehicle aircraft.common"}
		{"bf109_g6_fin_ai" inherit "vehicle aircraft.common"}
		
;------------------------------------USA	

		{"m2a4_stuart" inherit "vehicle tank.m3_stuart_early"}

		{"c-47_skytrain_dakota" inherit "vehicle aircraft.common"}
		{"c-47_skytrain_dakota_para_plane_player" inherit "vehicle aircraft.common"}
		{"c47_d_para_plane_ai" inherit "vehicle aircraft.common"}
		{"c47_d_para_plane_player" inherit "vehicle aircraft.common"}

		{"us-piper_j-3" inherit "vehicle aircraft.common"}
		{"us-piper_j-3_ai" inherit "vehicle aircraft.common"}

		{"us-b25" inherit "vehicle aircraft.common"}
		{"us-b25_ai" inherit "vehicle aircraft.common"}
		{"us-p-39" inherit "vehicle aircraft.common"}
		{"us-p-39_ai" inherit "vehicle aircraft.common"}
		{"us-p-40" inherit "vehicle aircraft.common_mp"}
		{"us-p-40_ai" inherit "vehicle aircraft.common_mp"}
		{"p-51mustang" inherit "vehicle aircraft.common"}
		{"p-51mustang_ai" inherit "vehicle aircraft.common"}

		{"f80a_rockets_127x12_ai" inherit "vehicle aircraft.common"}
		{"f80a_mk78x4_ai" inherit "vehicle aircraft.common"}
		{"f80a_450x2_ai" inherit "vehicle aircraft.common"}

		{"p47_d22_recon_ai" inherit "vehicle aircraft.common"}
		{"p47_d22_m8_ai" inherit "vehicle aircraft.common"}
		{"p47_d22_hvar_ai" inherit "vehicle aircraft.common"}
		{"p47_d22_250lb_ai" inherit "vehicle aircraft.common"}

;------------------------------------ENG

		{"blenheim_mk1_eng_ai" inherit "vehicle aircraft.common"}
		{"blenheim_mk1_eng_recon_ai" inherit "vehicle aircraft.common"}
		{"hurribomber_mk2c_ai" inherit "vehicle aircraft.common"}
		{"hurricane_mk1a_ai" inherit "vehicle aircraft.common"}
		{"typhoon_mk1b_ai" inherit "vehicle aircraft.common"}
		{"typhoon_mk1b_recon_ai" inherit "vehicle aircraft.common"}
	
;========================================================== /ARm END


;//		{"t34_100" inherit "vehicle tank.t3485_mace"}