; Third Person Control Definitions for new units

;========================================================== ARm BEGIN	
;==================================== STATIC

;------------------------------------GER static
		{"37mm_flak37_stand" inherit "vehicle atgun.pak40"}
		{"flak38_stand" inherit "vehicle atgun.flak38"}
		{"50mm_flak41_stand" inherit "vehicle atgun.flak41"}
		{"75mm_pak9738_late_stand" inherit "vehicle atgun.pak40"}
		{"80mm_sgrw34_stand" inherit "vehicle mortar.common"}
		{"88mm_flak18_stand" inherit "vehicle atgun.flak18"}
		{"105mm_flak38_stat" inherit "vehicle atgun.flak18 "}
		{"105mm_flak38_stand" inherit "vehicle atgun.flak18"}
		{"105mm_lefh18_stand" inherit "vehicle vehicle artillery.common"}
		{"120mm_sgrw42_stand" inherit "vehicle mortar.common"}
		{"28cm_wkspr_stan" inherit "vehicle artillery.common"}

		{"150mm_sw34_stand" inherit "vehicle generic.searchlight"}

		{"panzer1f_stand" inherit "vehicle tank.panzer1f"}

		{"blitz3_6_engineering_stand" inherit "vehicle generic.unarmed"}
		{"blitz3_6_fuel_stand" inherit "vehicle generic.unarmed"}
		{"blitz3_6_radio_stand" inherit "vehicle generic.unarmed"}
		{"kettenkrad_stand" inherit "vehicle small.unarmed"}
		{"opel_maultier_stand" inherit "vehicle generic.unarmed"}
		
		{"inf_crate_ger_stand" inherit "vehicle high_mg.common"}
		{"ammo_trailer_stand" inherit "vehicle medium_mg.common"}
		{"browning_m2_lafette2_stand" inherit "vehicle medium_mg.common"}
		
		{"mg42_lafette_tower_stand" inherit "vehicle medium_mg.common"}
		{"mg34_lafette_tower_stand" inherit "vehicle medium_mg.common"}
		{"mg34_tripod_stand" inherit "vehicle medium_mg.common"}
		{"mg42_tripod_stand" inherit "vehicle medium_mg.common"}
		{"mg131_lafette_big_stand" inherit "vehicle medium_mg.common"}
		{"mg131_lafette_stand" inherit "vehicle medium_mg.common"}
		{"mg131_lafette_ger_bunker_stand" inherit "vehicle medium_mg.common"}		
;------------------------------------USSR static

		{"stalinetz60_stand" inherit "vehicle generic.unarmed"}
		{"76mm_m1938_stand" inherit "vehicle atgun.52k"}
		{"37mm_61k_stand" inherit "vehicle atgun.61k"}
		{"85mm_52k_stand" inherit "vehicle atgun.52k"}
		{"107mm_m1910_30_stand" inherit "vehicle artillery.common"}
		{"120mm_pm38_stand" inherit "vehicle mortar.common"}
		{"122mm_m30_stand" inherit "vehicle artillery.common"}
		{"122mm_m1910_stand" inherit "vehicle artillery.common"}
		{"203mm_b4_stand" inherit "vehicle artillery.common"}
		{"dshk_aa_stand" inherit "vehicle high_mg.common"}
		{"kpv_1944_dzot" inherit "vehicle medium_mg.common"}
		{"maxim_x4_stand" inherit "vehicle aamg.maxim_quad"}
		{"300mm_m30_stand" inherit "vehicle artillery.common"}
		{"100mm_bs3_stand" inherit "vehicle artillery.common"}

		{"gaz_aaa_supply_stand" inherit "vehicle generic.unarmed"}
		{"gaz_fuel_stand" inherit "vehicle generic.unarmed"}
		{"zis5eng_stand" inherit "vehicle generic.unarmed"}

		{"inf_crate_rus_stand" inherit "vehicle high_mg.common"}
		
		{"maxim_tower_stand" inherit "vehicle medium_mg.common"}
	
		{"dp_tripod" inherit "vehicle medium_mg.common"}
		{"dp_tripod_stand" inherit "vehicle medium_mg.common"}

;------------------------------------FIN static

		{"40mm_itk38b_stand" inherit "vehicle atgun.bofors"}
		{"panzernest_krab_stand" inherit "vehicle cannon.panzernest"}
		{"20mm_itk35_stand" inherit "vehicle atgun.itk35"}
		{"20mm_itk40_stand" inherit "vehicle atgun.itk35"}
		{"75mm_itk37_stand" inherit "vehicle atgun.flak18"}
		{"75mm_itk44_stand" inherit "vehicle atgun.flak18 "}
		{"76mm_itk31_stand" inherit "vehicle atgun.itk31"}
		{"105mm_k34_stand" inherit "vehicle artillery.common"}
		{"120mm_krh40_stand" inherit "vehicle mortar.common"}
		{"ds39_fin_stand" inherit "vehicle low_med_mg.common"}
		{"50mm_flak41_bunker_stand" inherit "vehicle atgun.flak41"}
		{"50mm_krh38_stand" inherit "vehicle mortar.common"}
		{"155mm_h17_stand" inherit "vehicle artillery.common"}
		{"150mm_rkh41_stand" inherit "vehicle artillery.common"}


		{"ford_3ton_ammo_stand" inherit "vehicle generic.unarmed"}
		{"ford_3ton_eng_stand" inherit "vehicle generic.unarmed"}
		{"ford_3ton_fuel_stand" inherit "vehicle		generic.unarmed "}

		{"inf_crate_stand" inherit "vehicle high_mg.common"}
		
		{"maxim_tower_fin_stand" inherit "vehicle medium_mg.common"}
		
		{"75mm_pak40_stand" inherit "vehicle atgun.pak40"}

		{"dt_tripod_stand" inherit "vehicle medium_mg.common"}

;------------------------------------USA static
        {"inf_eng_crate_usa" inherit "vehicle high_mg.common"}		

		{"57mm_m1_late_stand" inherit "vehicle atgun.57mm_m1"}

		{"40mm_m1_stand" inherit "vehicle atgun.40mm_m1"}
		
		{"105mm_m2a1_stand" inherit "vehicle artillery.common"}
		
		{"81mm_m1_stand" inherit "vehicle mortar.common"}
		{"203mm_m1_stand" inherit "vehicle artillery.common"}
		{"m2_30cal_tower" inherit "vehicle medium_mg.common"}
		
		{"inf_crate_usa_stand" inherit "vehicle high_mg.common"}
		{"50calM2_lafette_stand" inherit "vehicle high_mg.common"}
		{"90mm_m1a1_stand" inherit "vehicle atgun.90mm_m1a1"}

		{"cckw_engineer_late_stand" inherit "vehicle vehicle.gmc_mg"}
		{"cckw_fuel_stand" inherit "vehicle generic.unarmed"}
		{"cckw_redball_stand" inherit "vehicle vehicle.gmc_mg"}
		{"cckw_art_ammo_stand" inherit "vehicle generic.unarmed"}
		
		
;==================================== /STATIC
;========================================================== /ARm END
