{"sand sandbag onestage construction"
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}



;============================================================================== GER CONSTRUCTIONS ==============================================================================

;---------------------------------------------- ger_tobruk_h39
{"ger_tobruk_h39" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"supply_point_ger" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"supply_point_ger_crate" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_regelbau_flak_position_2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_regelbau_flak_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- ger_watch_tower_mg
{"ger_watch_tower_mg" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- tobruk
{"tobruk" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"tobruk_mgun" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"tobruk_h39" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- ger_arty_bunker
{"ger_arty_bunker" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"155mm_gpf_platform" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- ger_mg_casemate
{"ger_mg_casemate" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}



;============================================================================== USSR CONSTRUCTIONS ==============================================================================

;---------------------------------------------- ussr_at_heavy_emplacement
{"ussr_at_heavy_emplacement" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- ussr_at_heavy_emplacement_plank
{"ussr_at_heavy_emplacement_plank" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- ussr_watch_tower_mg
{"ussr_watch_tower_mg" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- ussr_mg_casemate

{"ussr_mg_casemate" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;============================================================================== FIN CONSTRUCTIONS ==============================================================================

{"supply_point_fin" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- mg_casemate
{"mg_casemate" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- fin_watch_tower_mg

{"fin_watch_tower_mg" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}



;---------------------------------------------- fin_bunker_flak
{"fin_bunker_flak" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;============================================================================== USSR CONSTRUCTIONS ==============================================================================

{"supply_point_rus" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- usa_watch_tower_m2_30cal
{"usa_watch_tower_m2_30cal" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- trench_pillbox_usa
{"trench_pillbox_usa" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- trench_pillbox
{"trench_pillbox" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- trench_dirt_fire_position2
{"trench_dirt_fire_position2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- trench_dirt_exit_pillbox
{"trench_dirt_exit_pillbox" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- netting_square
{"netting_square" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- usa_heavy_arty_static_position
{"usa_heavy_arty_static_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}




;---------------------------------------------- usa_flak_ring



;---------------------------------------------- /usa_flak_ring
;============================================================================== / ALL NATIONS CONSTRUCTIONS END ==============================================================================

;============================================================================== ALL NATIONS UNITS BEGIN

;============================================================================== GER UNITS
;---------------------------------------------- 105mm_flak38_stat


;---------------------------------------------- inf_crate_ger_stand
{"inf_crate_ger_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}


;---------------------------------------------- ger_mg_lafette_mg34_reg
{"mg34_tripod_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}


;============================================================================== USSR UNITS

{"inf_crate_rus_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- inf_crate_rus_stand
{"inf_crate_rus_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- dp_tripod_stand
{"dp_tripod_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- sg43_stand
{"sg43_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- 100mm_bs3_stand
{"100mm_bs3_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- 300mm_m30_stand
{"300mm_m30_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- 203mm_m1_stand
{"203mm_m1_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- 85mm_52k_bot
{"85mm_52k_bot" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- ussr_at_static_position
{"76mm_m1938_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;============================================================================== FIN UNITS

;---------------------------------------------- mortar_foxhole
{"50mm_krh38_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- 155mm_h17_stand
{"155mm_h17_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- inf_crate_stand
{"inf_crate_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- 50mm_flak41_bunker_stand
{"50mm_flak41_bunker_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- bot
{"75mm_itk37_bot" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}


;---------------------------------------------- fin_150mm_rkh41_position_reg
{"150mm_rkh41_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- fin_mg_lafette_dt_reg
{"dt_tripod_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}


;============================================================================== USA CONSTRUCTION

{"supply_point_usa" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}




{"grfp_plank_trench_big" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"atr04" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"atr03" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"atr02" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"atr01" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"atr01" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}





{"aar04" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"aar03" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"aar02" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"aar01" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"supply_point_usa_crate" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"40mm_m1_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"cckw_art_ammo_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"cckw_redball_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"cckw_fuel_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"cckw_engineer_late_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}


{"plank_trench_big" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"plank_trench" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"75mm_pak40_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"ger_regelbau_pak" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"usa_flak_ring" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"90mm_m1a1_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"50calM2_lafette_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"inf_crate_usa_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"trench_pillbox_usa" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"watch_tower_m2_30cal" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"m2_30cal_tower" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"usa_mortar_foxhole" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"usa_arty_static_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"maxim_tower_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"mg42_lafette_tower_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"mg34_lafette_tower_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"ds39_tower_fin_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"ussr_watch_tower_mg" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ussr_watch_tower_mg" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"usa_watch_tower_mg" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fin_watch_tower_mg" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"flak38_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}


{"pillbox" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fin_panzernest_krab" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}


{"panzernest_krab_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"regelbau_pole_freya" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"regelbaum_pole_freya_b" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"concrete_block_stair_02" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_regelbau_arty_bunker" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"aa_regelbau" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_arty_bunker" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"57mm_m1_late_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"tobruk_h39" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"tobruk" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_big_bunker" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"regel_bau_409" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_mg_bunker" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"tobruk_mgun" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_75at_static_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"guard_tower_small" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"watch_tower" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"sandbag_structured_curved_big" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"sandbag_structured_curved" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"inf_crate_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"flagpoint_ammo" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"sandbag_watchtower" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"guard_tower_small" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"sandbag_framed_straight" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win2"}
			else terrain_fx "snow"
				{tex_mod "win2"}
			else
				; do nothing
			}
		}
	}
}

{"antena" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win1"}
			else terrain_fx "snow"
				{tex_mod "win1"}
			else
				; do nothing
			}
		}
	}
}

{"netting_square_end" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"netting_square" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"75mm_pillbox_stage1" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"75mm_pillbox_stage2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"trench modular" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"mortar_foxhole" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"earth_pillbox" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"sandbag_watchtower" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"post_watchtower" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"sandbag_bunker_dummy_mg" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"sandbag_framed_curved" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"camp_fire_pot" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"watchtower" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"trench_dirt_emplacement" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"trench_dirt_fire_position2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"barbed_wire_poles" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ammo2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"crater_massive" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "snow"}
			else terrain_fx "snow"
				{tex_mod "snow"}
			else
				; do nothing
			}
		}
	}
}

{"planks_walkable2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"soldier_foxhole_x" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"trench_floor" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"crater_big" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "snow"}
			else terrain_fx "snow"
				{tex_mod "snow"}
			else
				; do nothing
			}
		}
	}
}

{"forest_bunker_entrance" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"watch_tower" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"antena1" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win1"}
			else terrain_fx "snow"
				{tex_mod "win1"}
			else
				; do nothing
			}
		}
	}
}



{"ammo2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ammo2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"arty_static_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"at_static_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"flak_gun_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_arty_static_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_at_static_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_mortar_foxhole" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"mortar_foxhole" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"trench_dirt_fire_position2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"big_foxhole" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"mg_foxhole" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ussr_arty_static_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ussr_at_static_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ussr_heavy_arty_static_position" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ussr_mortar_foxhole" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"dirt_lump_straight"
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "foxhole_deploy" "vehicle/deploy/foxhole/"}
			{play_sound "foxhole_deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"mound_eng"
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "foxhole_deploy" "vehicle/deploy/foxhole/"}
			{play_sound "foxhole_deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"sand-shuttering-box_3" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"crate_group_01" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"medic_hospital" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_coastal_gun" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}



{"barrel_water" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ger_bunker" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fin_bunker" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}



{"finnish_hut" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}










{"trench_pillbox" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}
	
{"fin_flak_gun_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}	

{"fin_coastal_gun" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}



{"crater_medium" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "ice"}
			else terrain_fx "snow"
				{tex_mod "snow"}
			else
				; do nothing
			}
		}
	}
}
					

;============================================================================== ALL NATIONS FLAGS ==============================================================================

;---------------------------------------------- flag_pole_large_ger
{"flag_pole_large_ger" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "ger"}
			else terrain_fx "snow"
				{tex_mod "ger"}
			else terrain_fx "ground"
				{tex_mod "ger"}
			else terrain_fx "sand"
				{tex_mod "ger"}
			else terrain_fx "grass"
				{tex_mod "ger"}
			else terrain_fx "mud"
				{tex_mod "ger"}			
			else
				{tex_mod "ger"}
			}
		}
	}
}

;---------------------------------------------- flag_pole_large_usa
{"flag_pole_large_usa" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "usa"}
			else terrain_fx "snow"
				{tex_mod "usa"}
			else terrain_fx "ground"
				{tex_mod "usa"}
			else terrain_fx "sand"
				{tex_mod "usa"}
			else terrain_fx "grass"
				{tex_mod "usa"}
			else terrain_fx "mud"
				{tex_mod "usa"}			
			else
				{tex_mod "usa"}
			}
		}
	}
}

;---------------------------------------------- flag_pole_usa
{"flag_pole_usa" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "usa"}
			else terrain_fx "snow"
				{tex_mod "usa"}
			else terrain_fx "ground"
				{tex_mod "usa"}
			else terrain_fx "sand"
				{tex_mod "usa"}
			else terrain_fx "grass"
				{tex_mod "usa"}
			else terrain_fx "mud"
				{tex_mod "usa"}			
			else
				{tex_mod "usa"}
			}
		}
	}
}

;---------------------------------------------- flag_pole_ger
{"flag_pole_ger" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "ger"}
			else terrain_fx "snow"
				{tex_mod "ger"}
			else terrain_fx "ground"
				{tex_mod "ger"}
			else terrain_fx "sand"
				{tex_mod "ger"}
			else terrain_fx "grass"
				{tex_mod "ger"}
			else terrain_fx "mud"
				{tex_mod "ger"}			
			else
				{tex_mod "ger"}
			}
		}
	}
}
		
;---------------------------------------------- flag_pole_fin		
{"flag_pole_fin" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "fin"}
			else terrain_fx "snow"
				{tex_mod "fin"}
			else terrain_fx "ground"
				{tex_mod "fin"}
			else terrain_fx "sand"
				{tex_mod "fin"}
			else terrain_fx "grass"
				{tex_mod "fin"}
			else terrain_fx "mud"
				{tex_mod "fin"}			
			else
				{tex_mod "fin"}
			}
		}
	}
}

;---------------------------------------------- flag_pole_small_ger
{"flag_pole_small_ger" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "ger"}
			else terrain_fx "snow"
				{tex_mod "ger"}
			else terrain_fx "ground"
				{tex_mod "ger"}
			else terrain_fx "sand"
				{tex_mod "ger"}
			else terrain_fx "grass"
				{tex_mod "ger"}
			else terrain_fx "mud"
				{tex_mod "ger"}			
			else
				{tex_mod "ger"}
			}
		}
	}
}

;---------------------------------------------- flag_pole_small_fin
{"flag_pole_small_fin" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "fin"}
			else terrain_fx "snow"
				{tex_mod "fin"}
			else terrain_fx "ground"
				{tex_mod "fin"}
			else terrain_fx "sand"
				{tex_mod "fin"}
			else terrain_fx "grass"
				{tex_mod "fin"}
			else terrain_fx "mud"
				{tex_mod "fin"}			
			else
				{tex_mod "fin"}
			}
		}
	}
}

;---------------------------------------------- flag_pole_small_usa
{"flag_pole_small_usa" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "usa"}
			else terrain_fx "snow"
				{tex_mod "usa"}
			else terrain_fx "ground"
				{tex_mod "usa"}
			else terrain_fx "sand"
				{tex_mod "usa"}
			else terrain_fx "grass"
				{tex_mod "usa"}
			else terrain_fx "mud"
				{tex_mod "usa"}			
			else
				{tex_mod "usa"}
			}
		}
	}
}


;============================================================================== ALL NATIONS CONSTRUCTIONS ==============================================================================

{"crate_group_02" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fin_bunker_at_flak" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}




{"pole_freya" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"rb40910_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"rb4099_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"rb4098_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"rb4097_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"rb4096_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"rb4095_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"rb4094_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"rb4094_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"rb4093_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"rb4092_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"rb4091_arm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"sandbag_heap_curved" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"emplacement_shelter1" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- 45mm_pillbox
{"45mm_pillbox" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- sandbag_heap_curved
{"sandbag_heap_curved" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- trench_dirt_mortar_engineer - mortar_pit

;---------------------------------------------- mortar_pit"
{"trench_dirt_mortar_engineer" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"mortar_pit" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}



;---------------------------------------------- sandbag_curved_heap
{"sandbag_curved_heap" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- trench_modular
{"trench_modular" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- sandbag_framed_straight
{"sandbag_framed_straight" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- tank_cover_small
{"tank_cover_small" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- tank_cover
{"tank_cover" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- sand-shuttering-box_5
{"sand-shuttering-box_5" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- sand-shuttering-box_2
{"sand-shuttering-box_2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- sandbag_heap_straight_90_indestructible
{"sandbag_heap_straight_90_indestructible" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- sand-shuttering-box_3
{"sand-shuttering-box_3" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- sandbag_structured_straight2_indestructible"
{"sandbag_structured_straight2_indestructible" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- sandbag_pile_indestructible
{"sandbag_pile_indestructible" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- casemate_1
{"casemate_1" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- casemate_2
{"casemate_2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- casemate_3
{"casemate_3" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- casemate_4
{"casemate_4" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"finnish_hut" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fin_hut_c01" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fin_hut_c02" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fin_hut_c03" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fin_hut_c04" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fin_hut_c05" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fin_hut_c06" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}			

{"fin_hut_c07" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}			
	
{"fin_hut_c08" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}				

{"fin_hut_c09" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}	

{"fin_hut_exterior01" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}	

{"fin_hut_exterior02" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}	

{"fin_hut_exterior03" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}	

{"fin_hut_exterior04" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}	

{"fin_hut_exterior05" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}	

{"fin_hut_exterior06" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}	

{"fin_hut_exterior07" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}					

{"fin_hut_exterior08" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}	

;---------------------------------------------- netting_square_big
{"netting_square_big" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- /usa_heavy_arty_static_position
{"trench_dirt_emplacement" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- trench_dirt_emplacement_ce
{"trench_dirt_emplacement_ce" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- trench_dirt_fire_position2
{"trench_dirt_fire_position2" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- trench_dirt_fire_position_ce
{"trench_dirt_fire_position_ce" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fr01" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fr02" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fr03" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fr04" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fr05" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fr06" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fr07" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c24" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c23" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c22" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c21" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c20" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c19" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c18" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c17" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c16" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c15" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c14" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c13" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c12" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c11" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c10" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c09" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c08" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c07" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c06" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c05" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c04" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c03" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c02" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ee_farm_c01" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"farm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"farm01" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}


{"eastern-europe_farm" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"ammo_boxes_07" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}



{"boxes_fortification_medium_small" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"boxes_fortification_medium" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"boxes1" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"crate_group_ammo_1" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"mts-fuel" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "blue_win"}
			else terrain_fx "snow"
				{tex_mod "blue_win"}
			else
				; do nothing
			}
		}
	}
}

{"ammo_box_07" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"supply_point_rus_crate" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"supply_point_fin_crate" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"fuel_storage_barrel" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"plank_trench1" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

;---------------------------------------------- all_concrete_bunker
{"all_concrete_bunker" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"rb1341" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"rb1342" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"rb1343" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"rb1344" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

{"rb1345" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "win"}
			else terrain_fx "snow"
				{tex_mod "win"}
			else
				; do nothing
			}
		}
	}
}

