

;============================================================================== GER UNITS ON CONSTRUCTIONS ==============================================================================

;---------------------------------------------- ger_tobruk_h39
{"h39_turret" 
	{on spawn
		{delay 0.2
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else tex_mod "win"
				{tex_mod "winter"}
			else
				; do nothing	
			}
		}
	}
}

{"45mm_21k_naval" 
	{on spawn
		{delay 0.2
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else tex_mod "win"
				{tex_mod "winter"}
			else
				; do nothing	
			}
		}
	}
}

;============================================================================== GER STAND VEHICLES ON CONSTRUCTIONS ==============================================================================

{"blitz3_6_engineering_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"blitz3_6_fuel_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"opel_maultier_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;============================================================================== USSR STAND VEHICLES ON CONSTRUCTIONS ==============================================================================

{"stalinetz60_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"zis5eng_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"gaz_aaa_supply_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"gaz_fuel_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

;============================================================================== FIN STAND VEHICLES ON CONSTRUCTIONS ==============================================================================

{"ford_3ton_ammo_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}

{"ford_3ton_eng_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}


{"ford_3ton_fuel_stand" 
	{on spawn
		{delay 0.1
			{spawn "building_smoke" "service_bone"}
			{link_sound "deploy" "vehicle/deploy"}
			{play_sound "deploy"}
			{if terrain_fx "ice"
				{tex_mod "winter"}
			else terrain_fx "snow"
				{tex_mod "winter"}
			else
				; do nothing
			}
		}
	}
}




;============================================================================== USA STAND VEHICLES ON CONSTRUCTIONS ==============================================================================
